version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: Europe/London
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      production-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types: [minor, patch]
      development-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: [minor, patch]
    ignore:
      - dependency-name: 'prisma'
        update-types: ['version-update:semver-major']
      - dependency-name: '@prisma/client'
        update-types: ['version-update:semver-major']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: Europe/London
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions:
        applies-to: version-updates
        update-types: [minor, patch]
