import type { VendorProfileData } from './types';

export const profiles: VendorProfileData[] = [
  {
    systemNameContains: 'Banner',
    foundedYear: 1968,
    headquarters: 'Reston, VA, USA',
    employees: '4,000+',
    marketShare: 'Leader (North America)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud', 'On-Premise', 'Hybrid'],
    techStack: 'Java / Oracle Database',
    apiStandards: ['REST', 'ETHOS Integration', 'LTI 1.3', 'OData'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SCIM'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP Moderate'],
    pricingModel: 'Per-FTE annual subscription',
    typicalCostRange: '£8–20 per student/year',
    implementationTime: '18–36 months',
    keyStrengths: ['Largest HE install base globally (1,400+ institutions)', 'Comprehensive financial aid (US Title IV compliance)', 'Deep Banner ecosystem of integrations', 'Ethos API layer for modern integration', 'Strong partner network'],
    knownLimitations: ['Ageing UI despite Banner 9 refresh', 'Heavy customisation culture slows upgrades', 'Weak outside North America', 'Limited native analytics — requires Cognos/Power BI', 'High total cost of ownership'],
    recentNews: 'Ellucian merged with Anthology in 2023, creating a combined HE technology giant. Banner 9.x continues active development with cloud-hosted options via Ellucian Cloud.',
  },
  {
    systemNameContains: 'SITS',
    foundedYear: 1999,
    headquarters: 'Bath, UK',
    employees: '2,000+',
    marketShare: 'Leader (UK & Australasia — ~65% UK market share)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['Cloud', 'On-Premise', 'Hybrid'],
    techStack: '.NET / Microsoft SQL Server',
    apiStandards: ['REST', 'SOAP', 'OData', 'HESA Data Futures native'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'UCAS API'],
    certifications: ['ISO 27001', 'Cyber Essentials Plus', 'GDPR compliant'],
    pricingModel: 'Annual site licence',
    typicalCostRange: '£150K–500K/year (institution size dependent)',
    implementationTime: '12–24 months',
    keyStrengths: ['Native HESA Data Futures compliance', 'Deep UCAS integration', 'UK regulatory expertise (OfS, UKVI, TEF)', 'Strong UK HE community network', 'Comprehensive student lifecycle coverage'],
    knownLimitations: ['Limited adoption outside UK/Australasia', 'Complex configuration requiring specialist staff', 'Slower release cycles than cloud-native competitors', 'eVision web interface ageing', 'Limited modern analytics capabilities'],
    recentNews: 'Tribal Group launched SITS Vision Cloud in 2023, offering SaaS deployment. The company has invested in cloud-native architecture and HESA Data Futures compliance.',
  },
  {
    systemNameContains: 'Workday Student',
    foundedYear: 2005,
    headquarters: 'Pleasanton, CA, USA',
    employees: '18,000+',
    marketShare: 'Challenger (fastest-growing — 650+ institutions)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud'],
    techStack: 'Proprietary cloud platform / Java microservices',
    apiStandards: ['REST', 'GraphQL', 'OData', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SCIM', 'Workday Integration Cloud'],
    certifications: ['SOC 1 Type II', 'SOC 2 Type II', 'ISO 27001', 'FedRAMP High', 'GDPR'],
    pricingModel: 'Per-student annual subscription (Student + HCM + Financials bundled)',
    typicalCostRange: '£25–60 per student/year (full suite)',
    implementationTime: '18–30 months',
    keyStrengths: ['Unified Student+HCM+Finance on single platform', 'Cloud-native — no upgrades needed', 'Strong analytics and reporting natively', 'Modern UX and mobile-first', 'Continuous feature delivery 2x per year'],
    knownLimitations: ['High subscription cost vs legacy systems', 'Limited UK-specific compliance (HESA requires customisation)', 'Implementation complexity for large institutions', 'Less financial aid depth than Banner for US institutions', 'Ecosystem less mature than legacy vendors'],
    recentNews: 'Workday Student passed 650 institutions in 2024 and announced enhanced UK compliance features for HESA Data Futures. Workday AI integration announced for student success predictions.',
  },
  {
    systemNameContains: 'Oracle Student Cloud',
    foundedYear: 2012,
    headquarters: 'Austin, TX, USA',
    employees: '160,000+ (Oracle Corp)',
    marketShare: 'Challenger (growing in US community colleges)',
    gartnerPosition: 'Visionary',
    deploymentModel: ['Cloud'],
    techStack: 'Oracle Cloud Infrastructure / Java',
    apiStandards: ['REST', 'OData', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Oracle Integration Cloud'],
    certifications: ['FedRAMP High', 'SOC 2 Type II', 'ISO 27001'],
    pricingModel: 'Per-student subscription',
    typicalCostRange: '£15–40 per student/year',
    implementationTime: '18–24 months',
    keyStrengths: ['Strong Oracle ERP integration (Finance, HCM)', 'Modern cloud-native architecture', 'Intelligent automation and AI features', 'Global data centres', 'Integrated Oracle Analytics'],
    knownLimitations: ['Limited UK-specific compliance features', 'Smaller HE install base than competitors', 'Implementation requires Oracle specialist expertise', 'Complex licensing model', 'Limited UK partner ecosystem'],
    recentNews: 'Oracle Student Cloud gained traction in US community college sector. Oracle announced AI-powered student success features in 2024 leveraging Oracle Cloud AI services.',
  },
  {
    systemNameContains: 'SAP',
    foundedYear: 1972,
    headquarters: 'Walldorf, Germany',
    employees: '105,000+ (SAP SE)',
    marketShare: 'Niche (strong in continental Europe)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['Cloud', 'On-Premise', 'Hybrid'],
    techStack: 'SAP HANA / ABAP / Java',
    apiStandards: ['REST', 'OData', 'SOAP'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SAP Integration Suite'],
    certifications: ['ISO 27001', 'SOC 2', 'BSI C5'],
    pricingModel: 'Module-based licensing',
    typicalCostRange: '£20–50 per student/year (full suite)',
    implementationTime: '24–48 months',
    keyStrengths: ['Tight integration with SAP Finance and HCM', 'Strong in German-speaking HE sector', 'Comprehensive HR-Student alignment', 'Robust compliance and audit trails', 'Enterprise-grade scalability'],
    knownLimitations: ['Limited adoption outside continental Europe', 'Very high implementation cost and complexity', 'Requires SAP-specialist staff', 'Student module less feature-rich than SIS specialists', 'Heavy ERP complexity for student use cases'],
    recentNews: 'SAP launched Student Lifecycle Management on SAP S/4HANA Cloud in 2023. Focus remains on continental European institutions already in the SAP ecosystem.',
  },
  {
    systemNameContains: 'Colleague',
    foundedYear: 1984,
    headquarters: 'Reston, VA, USA',
    employees: '4,000+ (Ellucian)',
    marketShare: 'Niche (US small-medium institutions)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['Cloud', 'On-Premise'],
    techStack: 'UniData / .NET',
    apiStandards: ['REST', 'Colleague Web API', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'Ethos'],
    certifications: ['SOC 2 Type II', 'FERPA compliant'],
    pricingModel: 'Per-FTE annual subscription',
    typicalCostRange: '£5–15 per student/year',
    implementationTime: '12–18 months',
    keyStrengths: ['Cost-effective for small/medium US institutions', 'Comprehensive SIS + Finance integration', 'Strong financial aid (Title IV)', 'Ethos Integration platform', 'Large US community college install base'],
    knownLimitations: ['Ageing UniData database architecture', 'Limited outside North America', 'Legacy UI requiring modernisation', 'Less analytics capability than competitors', 'Ellucian consolidation uncertainty'],
    recentNews: 'Ellucian announced Colleague will migrate to Ellucian Student (SaaS) platform over time. Current institutions offered cloud hosting on Ellucian Cloud.',
  },
  {
    systemNameContains: 'PeopleSoft',
    foundedYear: 1987,
    headquarters: 'Austin, TX, USA',
    employees: '160,000+ (Oracle)',
    marketShare: 'Established (large US public universities)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['On-Premise', 'Cloud (limited)'],
    techStack: 'PeopleTools / Oracle Database',
    apiStandards: ['REST', 'SOAP', 'OData'],
    integrationProtocols: ['SAML 2.0', 'PeopleSoft Integration Broker'],
    certifications: ['FedRAMP Moderate', 'FERPA compliant'],
    pricingModel: 'Perpetual licence + annual maintenance',
    typicalCostRange: '£10–25 per student/year (maintenance)',
    implementationTime: '24–48 months',
    keyStrengths: ['Deep functionality for large research universities', 'Strong alumni and advancement module', 'Comprehensive degree audit', 'Proven scalability', 'Strong Oracle Finance integration'],
    knownLimitations: ['End-of-primary-support lifecycle concern', 'Ageing technology stack', 'Very high implementation and maintenance cost', 'No cloud-native path', 'Oracle favouring Student Cloud migration'],
    recentNews: 'Oracle continues PeopleSoft Campus Solutions support but is encouraging migration to Oracle Student Cloud. PeopleSoft 9.2 receives regular updates but cloud strategy is unclear.',
  },
  {
    systemNameContains: 'Anthology Student',
    foundedYear: 2021,
    headquarters: 'Boca Raton, FL, USA',
    employees: '4,000+ (Anthology)',
    marketShare: 'Challenger',
    gartnerPosition: 'Challenger',
    deploymentModel: ['Cloud', 'On-Premise'],
    techStack: 'Microsoft Azure / .NET',
    apiStandards: ['REST', 'OData', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Anthology Alliance'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'Cyber Essentials+'],
    pricingModel: 'Per-student subscription',
    typicalCostRange: '£10–30 per student/year',
    implementationTime: '15–24 months',
    keyStrengths: ['Modern cloud architecture', 'Strong student success analytics', 'Integrated Blackboard LMS', 'AI-powered predictive insights', 'Growing international presence'],
    knownLimitations: ['Post-merger integration still maturing', 'Complex product portfolio causing confusion', 'Limited UK-specific compliance', 'Implementation expertise scarce outside US', 'Rapid product changes post-merger'],
    recentNews: 'Anthology (formed from Blackboard + Anthology merge) continues integrating product lines. Student and Reach CRM integration strengthened. UK market investment announced.',
  },
  {
    systemNameContains: 'Unit4',
    foundedYear: 1980,
    headquarters: 'Sliedrecht, Netherlands',
    employees: '5,000+',
    marketShare: 'Niche (Europe, strong in Nordics)',
    gartnerPosition: 'Visionary',
    deploymentModel: ['Cloud'],
    techStack: 'Unit4 ERPx cloud platform',
    apiStandards: ['REST', 'OData'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Unit4 Integration Hub'],
    certifications: ['ISO 27001', 'SOC 2', 'GDPR'],
    pricingModel: 'Per-student subscription',
    typicalCostRange: '£15–35 per student/year',
    implementationTime: '12–20 months',
    keyStrengths: ['Cloud-native architecture', 'Strong European HE focus', 'Unified student+finance+HR', 'Good multi-language support', 'Growing UK presence'],
    knownLimitations: ['Limited UK-specific regulatory compliance', 'Smaller partner ecosystem', 'Less mature student module than SIS specialists', 'Limited US market presence', 'Implementation expertise limited'],
    recentNews: 'Unit4 launched Student Management as standalone cloud product in 2022, targeting European universities migrating from legacy systems. Partnership with several Nordic universities.',
  },
  {
    systemNameContains: 'Ellucian Student',
    foundedYear: 2022,
    headquarters: 'Reston, VA, USA',
    employees: '4,000+ (Ellucian)',
    marketShare: 'Emerging',
    gartnerPosition: 'Visionary',
    deploymentModel: ['Cloud'],
    techStack: 'AWS / microservices / React',
    apiStandards: ['REST', 'GraphQL', 'LTI 1.3', 'Ethos'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SCIM'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP'],
    pricingModel: 'Per-student subscription (bundled suite)',
    typicalCostRange: '£20–45 per student/year',
    implementationTime: '12–24 months',
    keyStrengths: ['Modern cloud-native SaaS from ground up', 'Unified SIS+HCM+Finance+Platform', 'Modern UX replacing Banner/Colleague', 'Continuous deployment', 'Ethos Integration ecosystem'],
    knownLimitations: ['Very new — limited production deployments', 'Feature parity with Banner still building', 'US-centric — limited UK compliance', 'High cost for Banner migration path', 'Unproven at scale'],
    recentNews: 'Ellucian Student (SaaS) launched commercially in 2023. First production customers going live in 2024. Positioned as the long-term replacement for both Banner and Colleague.',
  },
  {
    systemNameContains: 'Canvas',
    foundedYear: 2008,
    headquarters: 'Salt Lake City, UT, USA',
    employees: '2,000+ (Instructure)',
    marketShare: 'Leader (US LMS market — 35% share)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud'],
    techStack: 'Ruby on Rails / AWS',
    apiStandards: ['REST', 'LTI 1.3', 'QTI', 'xAPI'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Canvas Data'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP Moderate', 'FERPA'],
    pricingModel: 'Per-user annual subscription',
    typicalCostRange: '£3–8 per student/year',
    implementationTime: '3–6 months',
    keyStrengths: ['Market-leading LMS adoption', 'Excellent instructor and student UX', 'SpeedGrader for efficient assessment', 'Strong LTI ecosystem (1,000+ integrations)', 'Canvas Studio for media'],
    knownLimitations: ['LMS only — no SIS functionality', 'Analytics require Canvas Data add-on', 'Pricing increased significantly post-Instructure IPO', 'Limited out-of-box UK compliance features', 'Dependency on SIS integration quality'],
    recentNews: 'Instructure acquired by Thesis Holdings in 2023. Canvas continued as market leader. Canvas AI features (Magic Lens) launched for automated grading assistance.',
  },
  {
    systemNameContains: 'Blackboard',
    foundedYear: 1997,
    headquarters: 'Boca Raton, FL, USA',
    employees: '4,000+ (Anthology)',
    marketShare: 'Established (declining — migration to Ultra)',
    gartnerPosition: 'Challenger',
    deploymentModel: ['Cloud'],
    techStack: 'Java / AWS',
    apiStandards: ['REST', 'LTI 1.3', 'QTI', 'xAPI'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'Cyber Essentials+'],
    pricingModel: 'Per-user annual subscription',
    typicalCostRange: '£3–8 per student/year',
    implementationTime: '3–9 months',
    keyStrengths: ['Ground-up redesign in Ultra (modern UX)', 'Strong discussion analytics', 'Progress tracking and milestone alerts', 'Anthology ecosystem integration', 'Flexible grading workflows'],
    knownLimitations: ['Mandatory migration from Classic to Ultra', 'Mixed reception to Ultra interface', 'Market share declining vs Canvas and Moodle', 'Anthology integration still maturing', 'Limited differentiation from Canvas'],
    recentNews: 'Blackboard Ultra migration deadline set for 2025. Anthology investing heavily in AI features for Ultra including AI Design Assistant and Intelligent Feedback.',
  },
  {
    systemNameContains: 'Moodle',
    foundedYear: 2002,
    headquarters: 'West Perth, Australia',
    employees: '500+ (Moodle HQ)',
    marketShare: 'Leader globally (40%+ market share by institutions)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['Cloud', 'On-Premise', 'Self-hosted'],
    techStack: 'PHP / MySQL / PostgreSQL',
    apiStandards: ['REST', 'LTI 1.3', 'xAPI', 'SCORM'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['ISO 27001 (MoodleCloud)', 'GDPR compliant'],
    pricingModel: 'Open source (free) + MoodleCloud hosting',
    typicalCostRange: '£0–3 per student/year (hosting costs)',
    implementationTime: '2–6 months',
    keyStrengths: ['Completely free open source', 'Largest global LMS community', 'Highly customisable via plugins', 'Moodle Workplace for corporate/HE training', 'No vendor lock-in'],
    knownLimitations: ['Requires technical expertise to self-host', 'UI dated vs commercial competitors', 'MoodleCloud performance at scale', 'Support depends on partner/community', 'Fragmented plugin quality'],
    recentNews: 'Moodle 4.x introduced significantly improved UX. Moodle Workplace continues growing for corporate training. AI features in development via community plugins.',
  },
  {
    systemNameContains: 'Brightspace',
    foundedYear: 1999,
    headquarters: 'Kitchener, Ontario, Canada',
    employees: '1,500+ (D2L)',
    marketShare: 'Challenger (strong in Canada, growing)',
    gartnerPosition: 'Visionary',
    deploymentModel: ['Cloud'],
    techStack: 'AWS / .NET',
    apiStandards: ['REST', 'LTI Advantage', 'QTI 3.0', 'xAPI', 'SCORM'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP Moderate', 'GDPR'],
    pricingModel: 'Per-user annual subscription',
    typicalCostRange: '£3–9 per student/year',
    implementationTime: '3–6 months',
    keyStrengths: ['First LMS certified for LTI Advantage', 'Strong adaptive learning engine', 'Excellent accessibility compliance (WCAG 2.1 AA)', 'Intelligent agents for early alert', 'Strong Canadian HE adoption'],
    knownLimitations: ['Smaller market share than Canvas/Blackboard', 'Limited UK market penetration', 'Partner ecosystem smaller than Canvas', 'Higher price than Moodle', 'Less name recognition than competitors'],
    recentNews: 'D2L launched Brightspace AI Suite in 2024 including AI-generated feedback, learning pathways, and predictive success scoring. Strong growth in UK HE sector reported.',
  },
  {
    systemNameContains: 'Aula',
    foundedYear: 2016,
    headquarters: 'London, UK',
    employees: '100–200',
    marketShare: 'Niche (UK-focused LXP)',
    gartnerPosition: null,
    deploymentModel: ['Cloud'],
    techStack: 'React / Node.js / AWS',
    apiStandards: ['REST', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['ISO 27001', 'Cyber Essentials+', 'GDPR'],
    pricingModel: 'Per-student annual subscription',
    typicalCostRange: '£5–12 per student/year',
    implementationTime: '1–3 months',
    keyStrengths: ['Community-first learning design', 'Excellent student engagement metrics', 'UK university focus and support', 'Evidence-based pedagogy design', 'Backed by Coventry University Group'],
    knownLimitations: ['LXP not full LMS — limited assessment tools', 'Small company — scale risk', 'Limited outside UK', 'No standalone grading/assessment depth', 'Integration ecosystem early stage'],
    recentNews: 'Aula raised Series B funding in 2023. Partnership with Coventry University Group deepened. AI-powered community moderation features launched.',
  },
  {
    systemNameContains: 'Anthology Reach',
    foundedYear: 2016,
    headquarters: 'Boca Raton, FL, USA',
    employees: '4,000+ (Anthology)',
    marketShare: 'Challenger (HE CRM)',
    gartnerPosition: 'Challenger',
    deploymentModel: ['Cloud'],
    techStack: 'Microsoft Dynamics 365 / Azure',
    apiStandards: ['REST', 'OData', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Microsoft Graph'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP'],
    pricingModel: 'Per-user subscription',
    typicalCostRange: '£15–40 per user/year',
    implementationTime: '6–12 months',
    keyStrengths: ['Built on Dynamics 365 — enterprise reliability', 'Full recruitment-to-alumni lifecycle', 'AI-powered engagement scoring', 'Strong Microsoft Teams integration', 'Comprehensive alumni advancement'],
    knownLimitations: ['Microsoft ecosystem lock-in', 'Requires CRM expertise to configure', 'Limited out-of-box HE workflows', 'Cost of Dynamics licences adds up', 'Complex to integrate with non-Microsoft SIS'],
    recentNews: 'Anthology Reach launched AI-powered student retention predictions in 2024. Integration with Blackboard Ultra for staff student view announced.',
  },
  {
    systemNameContains: 'Salesforce',
    foundedYear: 1999,
    headquarters: 'San Francisco, CA, USA',
    employees: '70,000+ (Salesforce)',
    marketShare: 'Leader (HE CRM — growing)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud'],
    techStack: 'Salesforce Platform / Apex / LWC',
    apiStandards: ['REST', 'SOAP', 'GraphQL', 'Bulk API'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'MuleSoft'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP High', 'GDPR'],
    pricingModel: 'Per-user subscription (Education Pricing)',
    typicalCostRange: '£25–80 per user/year',
    implementationTime: '6–18 months',
    keyStrengths: ['World-leading CRM platform', 'Einstein AI built-in', 'Extensive AppExchange ecosystem', 'EDA (Education Data Architecture)', 'Strong alumni and advancement'],
    knownLimitations: ['High cost — Salesforce Tax real', 'Requires Salesforce-specialist admins', 'Out-of-box HE workflows limited', 'Data model complexity', 'Not a replacement for SIS'],
    recentNews: 'Salesforce Education Cloud launched Education Cloud 360 in 2024. Einstein AI for student success predictions generally available. Partnership with Canvas via Instructure expanded.',
  },
  {
    systemNameContains: 'campusM',
    foundedYear: 2008,
    headquarters: 'Jerusalem, Israel (Ex Libris/Clarivate)',
    employees: '1,000+ (Ex Libris)',
    marketShare: 'Leader (UK mobile engagement — 50+ UK universities)',
    gartnerPosition: null,
    deploymentModel: ['Cloud'],
    techStack: 'React Native / Node.js / AWS',
    apiStandards: ['REST', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['ISO 27001', 'Cyber Essentials+', 'GDPR'],
    pricingModel: 'Per-institution annual licence',
    typicalCostRange: '£30K–100K/year',
    implementationTime: '2–4 months',
    keyStrengths: ['Dominant UK student mobile platform', 'Deep library (Ex Libris Alma) integration', 'Strong attendance tracking via Bluetooth/QR', 'Personalised student timetables', 'App-based communications'],
    knownLimitations: ['Mobile engagement only — not a full SIS/CRM', 'Limited analytics beyond engagement metrics', 'Requires SIS integration for data', 'Limited outside UK/EU', 'No standalone student record capability'],
    recentNews: 'campusM v7 launched in 2024 with AI personalisation and enhanced learning space booking. Ex Libris Rosetta digital preservation integration added.',
  },
  {
    systemNameContains: 'Modern Campus',
    foundedYear: 2014,
    headquarters: 'Scottsdale, AZ, USA',
    employees: '500+',
    marketShare: 'Leader (US continuing education)',
    gartnerPosition: null,
    deploymentModel: ['Cloud'],
    techStack: 'AWS / React / Node.js',
    apiStandards: ['REST', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['SOC 2 Type II', 'FERPA'],
    pricingModel: 'Per-institution / per-module subscription',
    typicalCostRange: '£20K–150K/year',
    implementationTime: '3–9 months',
    keyStrengths: ['Purpose-built for CE/non-traditional students', 'eCommerce enrollment native', 'AI-driven course recommendations', 'Strong employer/workforce alignment', '50+ financial reporting templates'],
    knownLimitations: ['US-centric — limited UK deployment', 'Not a full SIS for traditional students', 'Limited international regulatory compliance', 'Smaller brand recognition', 'Integration with legacy SIS complex'],
    recentNews: 'Modern Campus expanded to serve 700+ institutions in 2024. AI pathways engine launched for personalised CE/LLL recommendations. Partnership with LinkedIn Learning announced.',
  },
  {
    systemNameContains: 'Workday HCM',
    foundedYear: 2005,
    headquarters: 'Pleasanton, CA, USA',
    employees: '18,000+',
    marketShare: 'Leader (HE HCM)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud'],
    techStack: 'Workday Cloud Platform',
    apiStandards: ['REST', 'OData', 'Workday RaaS'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SCIM'],
    certifications: ['SOC 1&2 Type II', 'ISO 27001', 'FedRAMP High'],
    pricingModel: 'Per-employee subscription',
    typicalCostRange: '£25–70 per employee/year',
    implementationTime: '12–18 months',
    keyStrengths: ['Leading cloud HCM for HE', 'Unified with Workday Student and Financials', 'Excellent workforce analytics', 'Continuous delivery model', 'Strong payroll internationally'],
    knownLimitations: ['High subscription cost', 'UK payroll requires partner implementation', 'Complex configuration', 'Limited UCU/union-specific features', 'Heavy IT involvement for admin changes'],
    recentNews: 'Workday HCM announced AI-powered skills intelligence and workforce planning features in 2024. UK compliance updates for IR35 and HMRC reporting released.',
  },
  {
    systemNameContains: 'SJMS',
    foundedYear: 2022,
    headquarters: 'UK',
    employees: 'Internal development team',
    marketShare: 'Internal system — not commercially available',
    gartnerPosition: null,
    deploymentModel: ['Cloud'],
    techStack: 'Node.js / React / PostgreSQL / Docker',
    apiStandards: ['REST', 'Webhook / n8n'],
    integrationProtocols: ['OIDC', 'Keycloak SAML', 'HESA Data Futures'],
    certifications: ['ISO 27001 (in progress)', 'Cyber Essentials', 'GDPR'],
    pricingModel: 'Internal — not licensed',
    typicalCostRange: 'Internal development cost',
    implementationTime: 'Continuous development',
    keyStrengths: ['Purpose-built for UK HE regulatory compliance', 'HESA Data Futures native', 'Modern cloud-native architecture', 'Full HERM v3.1 gap analysis completed', 'Keycloak RBAC with 27+ roles'],
    knownLimitations: ['HERM audit: 84/130 SIS-relevant capabilities (64.6%)', 'Alumni management not yet implemented', 'Advanced analytics limited vs commercial systems', 'Small development team vs large vendors', 'No commercial support ecosystem'],
    recentNews: 'SJMS v4.0 reached Phase 1 completion in Q1 2026. Security audit completed (SEC-001 to SEC-006 all resolved). HESA compliance module in active development.',
  },
];
