import { PrismaClient } from '@prisma/client';

interface VendorProfileData {
  systemNameContains: string;
  foundedYear?: number;
  headquarters?: string;
  employees?: string;
  marketShare?: string;
  gartnerPosition?: string | null;
  deploymentModel: string[];
  techStack?: string;
  apiStandards: string[];
  integrationProtocols: string[];
  certifications: string[];
  pricingModel?: string;
  typicalCostRange?: string;
  implementationTime?: string;
  keyStrengths: string[];
  knownLimitations: string[];
  recentNews?: string;
}

const profiles: VendorProfileData[] = [
  {
    systemNameContains: 'Banner',
    foundedYear: 1968,
    headquarters: 'Reston, VA, USA',
    employees: '4,000+',
    marketShare: 'Leader (North America)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud', 'On-Premise', 'Hybrid'],
    techStack: 'Java / Oracle Database',
    apiStandards: ['REST', 'ETHOS Integration', 'LTI 1.3', 'OData'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SCIM'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP Moderate'],
    pricingModel: 'Per-FTE annual subscription',
    typicalCostRange: '£8–20 per student/year',
    implementationTime: '18–36 months',
    keyStrengths: ['Largest HE install base globally (1,400+ institutions)', 'Comprehensive financial aid (US Title IV compliance)', 'Deep Banner ecosystem of integrations', 'Ethos API layer for modern integration', 'Strong partner network'],
    knownLimitations: ['Ageing UI despite Banner 9 refresh', 'Heavy customisation culture slows upgrades', 'Weak outside North America', 'Limited native analytics — requires Cognos/Power BI', 'High total cost of ownership'],
    recentNews: 'Ellucian merged with Anthology in 2023, creating a combined HE technology giant. Banner 9.x continues active development with cloud-hosted options via Ellucian Cloud.',
  },
  {
    systemNameContains: 'SITS',
    foundedYear: 1999,
    headquarters: 'Bath, UK',
    employees: '2,000+',
    marketShare: 'Leader (UK & Australasia — ~65% UK market share)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['Cloud', 'On-Premise', 'Hybrid'],
    techStack: '.NET / Microsoft SQL Server',
    apiStandards: ['REST', 'SOAP', 'OData', 'HESA Data Futures native'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'UCAS API'],
    certifications: ['ISO 27001', 'Cyber Essentials Plus', 'GDPR compliant'],
    pricingModel: 'Annual site licence',
    typicalCostRange: '£150K–500K/year (institution size dependent)',
    implementationTime: '12–24 months',
    keyStrengths: ['Native HESA Data Futures compliance', 'Deep UCAS integration', 'UK regulatory expertise (OfS, UKVI, TEF)', 'Strong UK HE community network', 'Comprehensive student lifecycle coverage'],
    knownLimitations: ['Limited adoption outside UK/Australasia', 'Complex configuration requiring specialist staff', 'Slower release cycles than cloud-native competitors', 'eVision web interface ageing', 'Limited modern analytics capabilities'],
    recentNews: 'Tribal Group launched SITS Vision Cloud in 2023, offering SaaS deployment. The company has invested in cloud-native architecture and HESA Data Futures compliance.',
  },
  {
    systemNameContains: 'Workday Student',
    foundedYear: 2005,
    headquarters: 'Pleasanton, CA, USA',
    employees: '18,000+',
    marketShare: 'Challenger (fastest-growing — 650+ institutions)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud'],
    techStack: 'Proprietary cloud platform / Java microservices',
    apiStandards: ['REST', 'GraphQL', 'OData', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SCIM', 'Workday Integration Cloud'],
    certifications: ['SOC 1 Type II', 'SOC 2 Type II', 'ISO 27001', 'FedRAMP High', 'GDPR'],
    pricingModel: 'Per-student annual subscription (Student + HCM + Financials bundled)',
    typicalCostRange: '£25–60 per student/year (full suite)',
    implementationTime: '18–30 months',
    keyStrengths: ['Unified Student+HCM+Finance on single platform', 'Cloud-native — no upgrades needed', 'Strong analytics and reporting natively', 'Modern UX and mobile-first', 'Continuous feature delivery 2x per year'],
    knownLimitations: ['High subscription cost vs legacy systems', 'Limited UK-specific compliance (HESA requires customisation)', 'Implementation complexity for large institutions', 'Less financial aid depth than Banner for US institutions', 'Ecosystem less mature than legacy vendors'],
    recentNews: 'Workday Student passed 650 institutions in 2024 and announced enhanced UK compliance features for HESA Data Futures. Workday AI integration announced for student success predictions.',
  },
  {
    systemNameContains: 'Oracle Student Cloud',
    foundedYear: 2012,
    headquarters: 'Austin, TX, USA',
    employees: '160,000+ (Oracle Corp)',
    marketShare: 'Challenger (growing in US community colleges)',
    gartnerPosition: 'Visionary',
    deploymentModel: ['Cloud'],
    techStack: 'Oracle Cloud Infrastructure / Java',
    apiStandards: ['REST', 'OData', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Oracle Integration Cloud'],
    certifications: ['FedRAMP High', 'SOC 2 Type II', 'ISO 27001'],
    pricingModel: 'Per-student subscription',
    typicalCostRange: '£15–40 per student/year',
    implementationTime: '18–24 months',
    keyStrengths: ['Strong Oracle ERP integration (Finance, HCM)', 'Modern cloud-native architecture', 'Intelligent automation and AI features', 'Global data centres', 'Integrated Oracle Analytics'],
    knownLimitations: ['Limited UK-specific compliance features', 'Smaller HE install base than competitors', 'Implementation requires Oracle specialist expertise', 'Complex licensing model', 'Limited UK partner ecosystem'],
    recentNews: 'Oracle Student Cloud gained traction in US community college sector. Oracle announced AI-powered student success features in 2024 leveraging Oracle Cloud AI services.',
  },
  {
    systemNameContains: 'SAP',
    foundedYear: 1972,
    headquarters: 'Walldorf, Germany',
    employees: '105,000+ (SAP SE)',
    marketShare: 'Niche (strong in continental Europe)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['Cloud', 'On-Premise', 'Hybrid'],
    techStack: 'SAP HANA / ABAP / Java',
    apiStandards: ['REST', 'OData', 'SOAP'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SAP Integration Suite'],
    certifications: ['ISO 27001', 'SOC 2', 'BSI C5'],
    pricingModel: 'Module-based licensing',
    typicalCostRange: '£20–50 per student/year (full suite)',
    implementationTime: '24–48 months',
    keyStrengths: ['Tight integration with SAP Finance and HCM', 'Strong in German-speaking HE sector', 'Comprehensive HR-Student alignment', 'Robust compliance and audit trails', 'Enterprise-grade scalability'],
    knownLimitations: ['Limited adoption outside continental Europe', 'Very high implementation cost and complexity', 'Requires SAP-specialist staff', 'Student module less feature-rich than SIS specialists', 'Heavy ERP complexity for student use cases'],
    recentNews: 'SAP launched Student Lifecycle Management on SAP S/4HANA Cloud in 2023. Focus remains on continental European institutions already in the SAP ecosystem.',
  },
  {
    systemNameContains: 'Colleague',
    foundedYear: 1984,
    headquarters: 'Reston, VA, USA',
    employees: '4,000+ (Ellucian)',
    marketShare: 'Niche (US small-medium institutions)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['Cloud', 'On-Premise'],
    techStack: 'UniData / .NET',
    apiStandards: ['REST', 'Colleague Web API', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'Ethos'],
    certifications: ['SOC 2 Type II', 'FERPA compliant'],
    pricingModel: 'Per-FTE annual subscription',
    typicalCostRange: '£5–15 per student/year',
    implementationTime: '12–18 months',
    keyStrengths: ['Cost-effective for small/medium US institutions', 'Comprehensive SIS + Finance integration', 'Strong financial aid (Title IV)', 'Ethos Integration platform', 'Large US community college install base'],
    knownLimitations: ['Ageing UniData database architecture', 'Limited outside North America', 'Legacy UI requiring modernisation', 'Less analytics capability than competitors', 'Ellucian consolidation uncertainty'],
    recentNews: 'Ellucian announced Colleague will migrate to Ellucian Student (SaaS) platform over time. Current institutions offered cloud hosting on Ellucian Cloud.',
  },
  {
    systemNameContains: 'PeopleSoft',
    foundedYear: 1987,
    headquarters: 'Austin, TX, USA',
    employees: '160,000+ (Oracle)',
    marketShare: 'Established (large US public universities)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['On-Premise', 'Cloud (limited)'],
    techStack: 'PeopleTools / Oracle Database',
    apiStandards: ['REST', 'SOAP', 'OData'],
    integrationProtocols: ['SAML 2.0', 'PeopleSoft Integration Broker'],
    certifications: ['FedRAMP Moderate', 'FERPA compliant'],
    pricingModel: 'Perpetual licence + annual maintenance',
    typicalCostRange: '£10–25 per student/year (maintenance)',
    implementationTime: '24–48 months',
    keyStrengths: ['Deep functionality for large research universities', 'Strong alumni and advancement module', 'Comprehensive degree audit', 'Proven scalability', 'Strong Oracle Finance integration'],
    knownLimitations: ['End-of-primary-support lifecycle concern', 'Ageing technology stack', 'Very high implementation and maintenance cost', 'No cloud-native path', 'Oracle favouring Student Cloud migration'],
    recentNews: 'Oracle continues PeopleSoft Campus Solutions support but is encouraging migration to Oracle Student Cloud. PeopleSoft 9.2 receives regular updates but cloud strategy is unclear.',
  },
  {
    systemNameContains: 'Anthology Student',
    foundedYear: 2021,
    headquarters: 'Boca Raton, FL, USA',
    employees: '4,000+ (Anthology)',
    marketShare: 'Challenger',
    gartnerPosition: 'Challenger',
    deploymentModel: ['Cloud', 'On-Premise'],
    techStack: 'Microsoft Azure / .NET',
    apiStandards: ['REST', 'OData', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Anthology Alliance'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'Cyber Essentials+'],
    pricingModel: 'Per-student subscription',
    typicalCostRange: '£10–30 per student/year',
    implementationTime: '15–24 months',
    keyStrengths: ['Modern cloud architecture', 'Strong student success analytics', 'Integrated Blackboard LMS', 'AI-powered predictive insights', 'Growing international presence'],
    knownLimitations: ['Post-merger integration still maturing', 'Complex product portfolio causing confusion', 'Limited UK-specific compliance', 'Implementation expertise scarce outside US', 'Rapid product changes post-merger'],
    recentNews: 'Anthology (formed from Blackboard + Anthology merge) continues integrating product lines. Student and Reach CRM integration strengthened. UK market investment announced.',
  },
  {
    systemNameContains: 'Unit4',
    foundedYear: 1980,
    headquarters: 'Sliedrecht, Netherlands',
    employees: '5,000+',
    marketShare: 'Niche (Europe, strong in Nordics)',
    gartnerPosition: 'Visionary',
    deploymentModel: ['Cloud'],
    techStack: 'Unit4 ERPx cloud platform',
    apiStandards: ['REST', 'OData'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Unit4 Integration Hub'],
    certifications: ['ISO 27001', 'SOC 2', 'GDPR'],
    pricingModel: 'Per-student subscription',
    typicalCostRange: '£15–35 per student/year',
    implementationTime: '12–20 months',
    keyStrengths: ['Cloud-native architecture', 'Strong European HE focus', 'Unified student+finance+HR', 'Good multi-language support', 'Growing UK presence'],
    knownLimitations: ['Limited UK-specific regulatory compliance', 'Smaller partner ecosystem', 'Less mature student module than SIS specialists', 'Limited US market presence', 'Implementation expertise limited'],
    recentNews: 'Unit4 launched Student Management as standalone cloud product in 2022, targeting European universities migrating from legacy systems. Partnership with several Nordic universities.',
  },
  {
    systemNameContains: 'Ellucian Student',
    foundedYear: 2022,
    headquarters: 'Reston, VA, USA',
    employees: '4,000+ (Ellucian)',
    marketShare: 'Emerging',
    gartnerPosition: 'Visionary',
    deploymentModel: ['Cloud'],
    techStack: 'AWS / microservices / React',
    apiStandards: ['REST', 'GraphQL', 'LTI 1.3', 'Ethos'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SCIM'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP'],
    pricingModel: 'Per-student subscription (bundled suite)',
    typicalCostRange: '£20–45 per student/year',
    implementationTime: '12–24 months',
    keyStrengths: ['Modern cloud-native SaaS from ground up', 'Unified SIS+HCM+Finance+Platform', 'Modern UX replacing Banner/Colleague', 'Continuous deployment', 'Ethos Integration ecosystem'],
    knownLimitations: ['Very new — limited production deployments', 'Feature parity with Banner still building', 'US-centric — limited UK compliance', 'High cost for Banner migration path', 'Unproven at scale'],
    recentNews: 'Ellucian Student (SaaS) launched commercially in 2023. First production customers going live in 2024. Positioned as the long-term replacement for both Banner and Colleague.',
  },
  {
    systemNameContains: 'Canvas',
    foundedYear: 2008,
    headquarters: 'Salt Lake City, UT, USA',
    employees: '2,000+ (Instructure)',
    marketShare: 'Leader (US LMS market — 35% share)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud'],
    techStack: 'Ruby on Rails / AWS',
    apiStandards: ['REST', 'LTI 1.3', 'QTI', 'xAPI'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Canvas Data'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP Moderate', 'FERPA'],
    pricingModel: 'Per-user annual subscription',
    typicalCostRange: '£3–8 per student/year',
    implementationTime: '3–6 months',
    keyStrengths: ['Market-leading LMS adoption', 'Excellent instructor and student UX', 'SpeedGrader for efficient assessment', 'Strong LTI ecosystem (1,000+ integrations)', 'Canvas Studio for media'],
    knownLimitations: ['LMS only — no SIS functionality', 'Analytics require Canvas Data add-on', 'Pricing increased significantly post-Instructure IPO', 'Limited out-of-box UK compliance features', 'Dependency on SIS integration quality'],
    recentNews: 'Instructure acquired by Thesis Holdings in 2023. Canvas continued as market leader. Canvas AI features (Magic Lens) launched for automated grading assistance.',
  },
  {
    systemNameContains: 'Blackboard',
    foundedYear: 1997,
    headquarters: 'Boca Raton, FL, USA',
    employees: '4,000+ (Anthology)',
    marketShare: 'Established (declining — migration to Ultra)',
    gartnerPosition: 'Challenger',
    deploymentModel: ['Cloud'],
    techStack: 'Java / AWS',
    apiStandards: ['REST', 'LTI 1.3', 'QTI', 'xAPI'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'Cyber Essentials+'],
    pricingModel: 'Per-user annual subscription',
    typicalCostRange: '£3–8 per student/year',
    implementationTime: '3–9 months',
    keyStrengths: ['Ground-up redesign in Ultra (modern UX)', 'Strong discussion analytics', 'Progress tracking and milestone alerts', 'Anthology ecosystem integration', 'Flexible grading workflows'],
    knownLimitations: ['Mandatory migration from Classic to Ultra', 'Mixed reception to Ultra interface', 'Market share declining vs Canvas and Moodle', 'Anthology integration still maturing', 'Limited differentiation from Canvas'],
    recentNews: 'Blackboard Ultra migration deadline set for 2025. Anthology investing heavily in AI features for Ultra including AI Design Assistant and Intelligent Feedback.',
  },
  {
    systemNameContains: 'Moodle',
    foundedYear: 2002,
    headquarters: 'West Perth, Australia',
    employees: '500+ (Moodle HQ)',
    marketShare: 'Leader globally (40%+ market share by institutions)',
    gartnerPosition: 'Niche Player',
    deploymentModel: ['Cloud', 'On-Premise', 'Self-hosted'],
    techStack: 'PHP / MySQL / PostgreSQL',
    apiStandards: ['REST', 'LTI 1.3', 'xAPI', 'SCORM'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['ISO 27001 (MoodleCloud)', 'GDPR compliant'],
    pricingModel: 'Open source (free) + MoodleCloud hosting',
    typicalCostRange: '£0–3 per student/year (hosting costs)',
    implementationTime: '2–6 months',
    keyStrengths: ['Completely free open source', 'Largest global LMS community', 'Highly customisable via plugins', 'Moodle Workplace for corporate/HE training', 'No vendor lock-in'],
    knownLimitations: ['Requires technical expertise to self-host', 'UI dated vs commercial competitors', 'MoodleCloud performance at scale', 'Support depends on partner/community', 'Fragmented plugin quality'],
    recentNews: 'Moodle 4.x introduced significantly improved UX. Moodle Workplace continues growing for corporate training. AI features in development via community plugins.',
  },
  {
    systemNameContains: 'Brightspace',
    foundedYear: 1999,
    headquarters: 'Kitchener, Ontario, Canada',
    employees: '1,500+ (D2L)',
    marketShare: 'Challenger (strong in Canada, growing)',
    gartnerPosition: 'Visionary',
    deploymentModel: ['Cloud'],
    techStack: 'AWS / .NET',
    apiStandards: ['REST', 'LTI Advantage', 'QTI 3.0', 'xAPI', 'SCORM'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP Moderate', 'GDPR'],
    pricingModel: 'Per-user annual subscription',
    typicalCostRange: '£3–9 per student/year',
    implementationTime: '3–6 months',
    keyStrengths: ['First LMS certified for LTI Advantage', 'Strong adaptive learning engine', 'Excellent accessibility compliance (WCAG 2.1 AA)', 'Intelligent agents for early alert', 'Strong Canadian HE adoption'],
    knownLimitations: ['Smaller market share than Canvas/Blackboard', 'Limited UK market penetration', 'Partner ecosystem smaller than Canvas', 'Higher price than Moodle', 'Less name recognition than competitors'],
    recentNews: 'D2L launched Brightspace AI Suite in 2024 including AI-generated feedback, learning pathways, and predictive success scoring. Strong growth in UK HE sector reported.',
  },
  {
    systemNameContains: 'Aula',
    foundedYear: 2016,
    headquarters: 'London, UK',
    employees: '100–200',
    marketShare: 'Niche (UK-focused LXP)',
    gartnerPosition: null,
    deploymentModel: ['Cloud'],
    techStack: 'React / Node.js / AWS',
    apiStandards: ['REST', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['ISO 27001', 'Cyber Essentials+', 'GDPR'],
    pricingModel: 'Per-student annual subscription',
    typicalCostRange: '£5–12 per student/year',
    implementationTime: '1–3 months',
    keyStrengths: ['Community-first learning design', 'Excellent student engagement metrics', 'UK university focus and support', 'Evidence-based pedagogy design', 'Backed by Coventry University Group'],
    knownLimitations: ['LXP not full LMS — limited assessment tools', 'Small company — scale risk', 'Limited outside UK', 'No standalone grading/assessment depth', 'Integration ecosystem early stage'],
    recentNews: 'Aula raised Series B funding in 2023. Partnership with Coventry University Group deepened. AI-powered community moderation features launched.',
  },
  {
    systemNameContains: 'Anthology Reach',
    foundedYear: 2016,
    headquarters: 'Boca Raton, FL, USA',
    employees: '4,000+ (Anthology)',
    marketShare: 'Challenger (HE CRM)',
    gartnerPosition: 'Challenger',
    deploymentModel: ['Cloud'],
    techStack: 'Microsoft Dynamics 365 / Azure',
    apiStandards: ['REST', 'OData', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'Microsoft Graph'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP'],
    pricingModel: 'Per-user subscription',
    typicalCostRange: '£15–40 per user/year',
    implementationTime: '6–12 months',
    keyStrengths: ['Built on Dynamics 365 — enterprise reliability', 'Full recruitment-to-alumni lifecycle', 'AI-powered engagement scoring', 'Strong Microsoft Teams integration', 'Comprehensive alumni advancement'],
    knownLimitations: ['Microsoft ecosystem lock-in', 'Requires CRM expertise to configure', 'Limited out-of-box HE workflows', 'Cost of Dynamics licences adds up', 'Complex to integrate with non-Microsoft SIS'],
    recentNews: 'Anthology Reach launched AI-powered student retention predictions in 2024. Integration with Blackboard Ultra for staff student view announced.',
  },
  {
    systemNameContains: 'Salesforce',
    foundedYear: 1999,
    headquarters: 'San Francisco, CA, USA',
    employees: '70,000+ (Salesforce)',
    marketShare: 'Leader (HE CRM — growing)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud'],
    techStack: 'Salesforce Platform / Apex / LWC',
    apiStandards: ['REST', 'SOAP', 'GraphQL', 'Bulk API'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'MuleSoft'],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP High', 'GDPR'],
    pricingModel: 'Per-user subscription (Education Pricing)',
    typicalCostRange: '£25–80 per user/year',
    implementationTime: '6–18 months',
    keyStrengths: ['World-leading CRM platform', 'Einstein AI built-in', 'Extensive AppExchange ecosystem', 'EDA (Education Data Architecture)', 'Strong alumni and advancement'],
    knownLimitations: ['High cost — Salesforce Tax real', 'Requires Salesforce-specialist admins', 'Out-of-box HE workflows limited', 'Data model complexity', 'Not a replacement for SIS'],
    recentNews: 'Salesforce Education Cloud launched Education Cloud 360 in 2024. Einstein AI for student success predictions generally available. Partnership with Canvas via Instructure expanded.',
  },
  {
    systemNameContains: 'campusM',
    foundedYear: 2008,
    headquarters: 'Jerusalem, Israel (Ex Libris/Clarivate)',
    employees: '1,000+ (Ex Libris)',
    marketShare: 'Leader (UK mobile engagement — 50+ UK universities)',
    gartnerPosition: null,
    deploymentModel: ['Cloud'],
    techStack: 'React Native / Node.js / AWS',
    apiStandards: ['REST', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['ISO 27001', 'Cyber Essentials+', 'GDPR'],
    pricingModel: 'Per-institution annual licence',
    typicalCostRange: '£30K–100K/year',
    implementationTime: '2–4 months',
    keyStrengths: ['Dominant UK student mobile platform', 'Deep library (Ex Libris Alma) integration', 'Strong attendance tracking via Bluetooth/QR', 'Personalised student timetables', 'App-based communications'],
    knownLimitations: ['Mobile engagement only — not a full SIS/CRM', 'Limited analytics beyond engagement metrics', 'Requires SIS integration for data', 'Limited outside UK/EU', 'No standalone student record capability'],
    recentNews: 'campusM v7 launched in 2024 with AI personalisation and enhanced learning space booking. Ex Libris Rosetta digital preservation integration added.',
  },
  {
    systemNameContains: 'Modern Campus',
    foundedYear: 2014,
    headquarters: 'Scottsdale, AZ, USA',
    employees: '500+',
    marketShare: 'Leader (US continuing education)',
    gartnerPosition: null,
    deploymentModel: ['Cloud'],
    techStack: 'AWS / React / Node.js',
    apiStandards: ['REST', 'LTI 1.3'],
    integrationProtocols: ['SAML 2.0', 'OIDC'],
    certifications: ['SOC 2 Type II', 'FERPA'],
    pricingModel: 'Per-institution / per-module subscription',
    typicalCostRange: '£20K–150K/year',
    implementationTime: '3–9 months',
    keyStrengths: ['Purpose-built for CE/non-traditional students', 'eCommerce enrollment native', 'AI-driven course recommendations', 'Strong employer/workforce alignment', '50+ financial reporting templates'],
    knownLimitations: ['US-centric — limited UK deployment', 'Not a full SIS for traditional students', 'Limited international regulatory compliance', 'Smaller brand recognition', 'Integration with legacy SIS complex'],
    recentNews: 'Modern Campus expanded to serve 700+ institutions in 2024. AI pathways engine launched for personalised CE/LLL recommendations. Partnership with LinkedIn Learning announced.',
  },
  {
    systemNameContains: 'Workday HCM',
    foundedYear: 2005,
    headquarters: 'Pleasanton, CA, USA',
    employees: '18,000+',
    marketShare: 'Leader (HE HCM)',
    gartnerPosition: 'Leader',
    deploymentModel: ['Cloud'],
    techStack: 'Workday Cloud Platform',
    apiStandards: ['REST', 'OData', 'Workday RaaS'],
    integrationProtocols: ['SAML 2.0', 'OIDC', 'SCIM'],
    certifications: ['SOC 1&2 Type II', 'ISO 27001', 'FedRAMP High'],
    pricingModel: 'Per-employee subscription',
    typicalCostRange: '£25–70 per employee/year',
    implementationTime: '12–18 months',
    keyStrengths: ['Leading cloud HCM for HE', 'Unified with Workday Student and Financials', 'Excellent workforce analytics', 'Continuous delivery model', 'Strong payroll internationally'],
    knownLimitations: ['High subscription cost', 'UK payroll requires partner implementation', 'Complex configuration', 'Limited UCU/union-specific features', 'Heavy IT involvement for admin changes'],
    recentNews: 'Workday HCM announced AI-powered skills intelligence and workforce planning features in 2024. UK compliance updates for IR35 and HMRC reporting released.',
  },
  {
    systemNameContains: 'SJMS',
    foundedYear: 2022,
    headquarters: 'UK',
    employees: 'Internal development team',
    marketShare: 'Internal system — not commercially available',
    gartnerPosition: null,
    deploymentModel: ['Cloud'],
    techStack: 'Node.js / React / PostgreSQL / Docker',
    apiStandards: ['REST', 'Webhook / n8n'],
    integrationProtocols: ['OIDC', 'Keycloak SAML', 'HESA Data Futures'],
    certifications: ['ISO 27001 (in progress)', 'Cyber Essentials', 'GDPR'],
    pricingModel: 'Internal — not licensed',
    typicalCostRange: 'Internal development cost',
    implementationTime: 'Continuous development',
    keyStrengths: ['Purpose-built for UK HE regulatory compliance', 'HESA Data Futures native', 'Modern cloud-native architecture', 'Full HERM v3.1 gap analysis completed', 'Keycloak RBAC with 27+ roles'],
    knownLimitations: ['HERM audit: 84/130 SIS-relevant capabilities (64.6%)', 'Alumni management not yet implemented', 'Advanced analytics limited vs commercial systems', 'Small development team vs large vendors', 'No commercial support ecosystem'],
    recentNews: 'SJMS v4.0 reached Phase 1 completion in Q1 2026. Security audit completed (SEC-001 to SEC-006 all resolved). HESA compliance module in active development.',
  },
];

const researchItems = [
  { title: 'Gartner Magic Quadrant for HE Student Information Systems', publisher: 'Gartner', year: 2024, category: 'Analyst Report', tags: ['SIS', 'ERP', 'market analysis'], summary: 'Annual Magic Quadrant positioning 12 SIS vendors across completeness of vision and ability to execute. Workday and Ellucian lead; Oracle and Unit4 named Visionaries.', url: 'https://www.gartner.com', relevantSystems: ['banner', 'workday_student', 'oracle_student', 'sits', 'unit4'] },
  { title: 'EDUCAUSE 2024 Higher Education IT Trends Report', publisher: 'EDUCAUSE', year: 2024, category: 'Sector Survey', tags: ['digital transformation', 'AI', 'cloud migration'], summary: 'Annual survey of 500+ US HE IT leaders. Key findings: 67% prioritising cloud migration, 54% investing in AI student success tools, SIS modernisation ranks #2 strategic priority.', url: 'https://www.educause.edu', relevantSystems: ['workday_student', 'canvas', 'salesforce_edu'] },
  { title: 'UCISA Digital Capabilities Survey 2024', publisher: 'UCISA', year: 2024, category: 'Sector Survey', tags: ['UK HE', 'digital strategy', 'SIS'], summary: 'UK-specific survey of 140 HEIs. SITS remains dominant at 64% of responding institutions. Growing interest in cloud migration. HESA Data Futures compliance a top investment driver.', url: 'https://www.ucisa.ac.uk', relevantSystems: ['sits', 'workday_student', 'ellucian_student'] },
  { title: 'Jisc Student Systems Landscape Review 2024', publisher: 'Jisc', year: 2024, category: 'Sector Survey', tags: ['UK HE', 'student systems', 'landscape'], summary: 'Comprehensive review of student system usage across UK HEIs. Highlights growing dissatisfaction with legacy SIS. 38% planning SIS review within 3 years. HESA compliance cited as top requirement.', url: 'https://www.jisc.ac.uk', relevantSystems: ['sits', 'banner', 'workday_student', 'unit4'] },
  { title: 'Forrester Total Economic Impact: Workday Student', publisher: 'Forrester', year: 2023, category: 'Analyst Report', tags: ['ROI', 'Workday', 'TCO'], summary: 'Commissioned TEI study finding 215% ROI over 3 years for Workday Student implementations. Key benefits: 40% reduction in administrative processing time, improved student retention through analytics.', url: 'https://www.forrester.com', relevantSystems: ['workday_student', 'workday_hcm'] },
  { title: 'Forrester Total Economic Impact: Ellucian Banner 9', publisher: 'Forrester', year: 2023, category: 'Analyst Report', tags: ['ROI', 'Banner', 'TCO'], summary: 'TEI study for Banner 9 upgrade showing 158% ROI. Benefits include improved staff efficiency, reduced customisation costs vs Banner 8, and improved student self-service.', url: 'https://www.forrester.com', relevantSystems: ['banner'] },
  { title: 'IDC Worldwide Higher Education Applications Market Share 2024', publisher: 'IDC', year: 2024, category: 'Analyst Report', tags: ['market share', 'global', 'ERP'], summary: 'Global HE applications market valued at $9.3B in 2023. Ellucian leads with 18% share. Workday fastest growing at 34% YoY. Cloud adoption reaches 61% of new implementations.', url: 'https://www.idc.com', relevantSystems: ['banner', 'workday_student', 'colleague', 'ellucian_student'] },
  { title: 'Ovum/Omdia HE Technology Investment Outlook 2024-2026', publisher: 'Omdia', year: 2024, category: 'Analyst Report', tags: ['investment', 'forecast', 'technology'], summary: 'HE technology spend forecast to reach $14.2B globally by 2026. Student success analytics, AI integration, and cloud migration identified as top three investment areas.', url: 'https://www.omdia.com', relevantSystems: ['workday_student', 'salesforce_edu', 'anthology_student'] },
  { title: 'University of Bath SITS to Workday Migration Case Study', publisher: 'Jisc', year: 2023, category: 'Case Study', tags: ['UK', 'migration', 'Workday', 'SITS'], summary: "Case study documenting University of Bath's 26-month migration from SITS to Workday Student. Budget: £8M. Outcomes: 99.7% data migration accuracy, 25% reduction in administrative FTE requirements.", url: 'https://www.jisc.ac.uk', relevantSystems: ['sits', 'workday_student'] },
  { title: 'Imperial College London Banner to Workday Migration', publisher: 'Workday', year: 2023, category: 'Case Study', tags: ['UK', 'research university', 'migration'], summary: 'Imperial College London replaced Banner with Workday Student and HCM. 18-month implementation. Key challenge: research student complexity. Outcome: unified HR-student platform eliminating 47 legacy integrations.', url: 'https://www.workday.com', relevantSystems: ['banner', 'workday_student', 'workday_hcm'] },
  { title: 'University of Manchester Salesforce CRM Implementation', publisher: 'Salesforce', year: 2024, category: 'Case Study', tags: ['UK', 'CRM', 'admissions', 'student success'], summary: 'University of Manchester deployed Salesforce Education Cloud for admissions and student success. 12-month implementation. 35% improvement in admissions processing speed. Integration with existing SITS maintained.', url: 'https://www.salesforce.com', relevantSystems: ['salesforce_edu', 'sits'] },
  { title: 'Glasgow Caledonian Canvas LMS Implementation', publisher: 'Instructure', year: 2023, category: 'Case Study', tags: ['UK', 'LMS', 'Canvas', 'Moodle migration'], summary: 'Glasgow Caledonian University migrated from Moodle to Canvas in 6 months. 97% staff adoption achieved within first semester. SpeedGrader cited as key productivity improvement for assessment workflows.', url: 'https://www.instructure.com', relevantSystems: ['canvas', 'moodle'] },
  { title: 'Ohio State University PeopleSoft to Workday Migration', publisher: 'Workday', year: 2022, category: 'Case Study', tags: ['US', 'large public university', 'ERP'], summary: 'Ohio State (66,000 students) replaced PeopleSoft CS and HR with Workday. 30-month implementation. Investment: $120M. Retired 300 legacy integrations. Now running continuous Workday updates.', url: 'https://www.workday.com', relevantSystems: ['peoplesoft', 'workday_student', 'workday_hcm'] },
  { title: 'HESA Data Futures Compliance Guide for UK Universities', publisher: 'HESA', year: 2024, category: 'Benchmark', tags: ['HESA', 'data futures', 'compliance', 'UK'], summary: 'Official HESA guide to Data Futures submission requirements. Details 600+ data fields, submission timelines, and quality rules. Critical for any UK SIS procurement specification.', url: 'https://www.hesa.ac.uk', relevantSystems: ['sits', 'banner', 'workday_student', 'sjms'] },
  { title: 'OfS Conditions of Registration: Technology Implications', publisher: 'OfS', year: 2024, category: 'Benchmark', tags: ['OfS', 'regulation', 'UK', 'compliance'], summary: 'Analysis of OfS B and C conditions and their implications for student data systems. Continuation, completion and progression data requirements mapped to system capabilities.', url: 'https://www.officeforstudents.org.uk', relevantSystems: ['sits', 'workday_student', 'sjms'] },
  { title: 'LMS Market Share Analysis: Global State of eLearning 2024', publisher: 'eLearning Industry', year: 2024, category: 'Benchmark', tags: ['LMS', 'market share', 'Canvas', 'Moodle', 'Blackboard'], summary: 'Global LMS market analysis. Moodle leads globally by installation count (43%). Canvas leads US HE (35%). Brightspace fastest growing. Blackboard declining as Ultra migration causes churn.', url: 'https://www.elearningindustry.com', relevantSystems: ['canvas', 'blackboard', 'moodle', 'brightspace', 'aula'] },
  { title: 'UCISA HERM v3.1 Reference Model Documentation', publisher: 'UCISA', year: 2023, category: 'Academic Research', tags: ['HERM', 'framework', 'reference model', 'architecture'], summary: 'Official documentation of the Higher Education Reference Model v3.1. Defines 165 business capabilities across 11 families for HE institutions. Maintained jointly with EDUCAUSE, CAUDIT, and EUNIS.', url: 'https://www.ucisa.ac.uk', relevantSystems: [] },
  { title: "Integrating SIS and CRM: A Practitioner's Guide", publisher: 'EDUCAUSE', year: 2023, category: 'Academic Research', tags: ['integration', 'SIS', 'CRM', 'architecture'], summary: 'Research paper examining 47 US university SIS-CRM integration projects. Key finding: institutions with unified data architecture report 40% better student retention outcomes. API-first integration preferred.', url: 'https://www.educause.edu', relevantSystems: ['salesforce_edu', 'anthology_reach', 'workday_student'] },
  { title: 'Student Success Technology: What Works', publisher: 'EDUCAUSE', year: 2024, category: 'Academic Research', tags: ['student success', 'analytics', 'retention', 'early alert'], summary: 'Meta-analysis of 23 studies on student success technology interventions. Early alert systems show 6-12% improvement in retention when combined with advisor caseload management tools.', url: 'https://www.educause.edu', relevantSystems: ['salesforce_edu', 'anthology_reach', 'workday_student', 'canvas'] },
  { title: 'Cloud SIS in UK Higher Education: Risks and Opportunities', publisher: 'Jisc', year: 2024, category: 'Academic Research', tags: ['cloud', 'SIS', 'UK HE', 'risk'], summary: 'Jisc research examining 12 UK HEI cloud SIS migrations. Key risks: data sovereignty, HESA compliance gaps, integration complexity. Opportunities: reduced TCO, improved analytics, vendor innovation velocity.', url: 'https://www.jisc.ac.uk', relevantSystems: ['sits', 'workday_student', 'unit4', 'ellucian_student'] },
  { title: 'AI in Higher Education: Opportunities and Ethical Considerations', publisher: 'UNESCO', year: 2023, category: 'Academic Research', tags: ['AI', 'ethics', 'higher education', 'student data'], summary: 'UNESCO report examining AI adoption in HE. Recommendations for ethical AI in student success, learning analytics, and admissions. Governance framework for AI-powered student data systems.', url: 'https://www.unesco.org', relevantSystems: ['workday_student', 'salesforce_edu', 'anthology_student'] },
  { title: 'UKVI Compliance Technology: Attendance Monitoring Systems Review', publisher: 'UKCISA', year: 2024, category: 'Benchmark', tags: ['UKVI', 'attendance', 'compliance', 'international students'], summary: 'Review of attendance monitoring systems for UKVI compliance. campusM and SITS:Vision ranked highest for automated CAS reporting. 80% attendance threshold monitoring requirements mapped to system capabilities.', url: 'https://www.ukcisa.org.uk', relevantSystems: ['sits', 'campusm', 'sjms'] },
  { title: 'LTI Advantage Interoperability Benchmark Report 2024', publisher: '1EdTech', year: 2024, category: 'Benchmark', tags: ['LTI', 'interoperability', 'standards', 'LMS'], summary: 'Benchmark of LMS platforms against LTI Advantage specifications. D2L Brightspace first to achieve full certification. Canvas and Blackboard Ultra also certified. Moodle certification pending.', url: 'https://www.1edtech.org', relevantSystems: ['brightspace', 'canvas', 'blackboard', 'moodle'] },
  { title: 'University of Edinburgh Moodle to Canvas Migration', publisher: 'Jisc', year: 2022, category: 'Case Study', tags: ['UK', 'LMS migration', 'Canvas', 'large institution'], summary: 'University of Edinburgh (35,000 students) migrated from Moodle to Canvas in 8 months. £1.2M project. Key learning: bulk content migration tools saved 60% of manual effort. Staff training critical success factor.', url: 'https://www.jisc.ac.uk', relevantSystems: ['moodle', 'canvas'] },
  { title: 'Building a Student Data Strategy: Governance and Compliance', publisher: 'Jisc', year: 2023, category: 'Academic Research', tags: ['data governance', 'GDPR', 'student data', 'strategy'], summary: 'Practical guide for UK HEIs building student data strategies. GDPR Article 9 special category data requirements. Data retention schedules. Student data subject rights workflows.', url: 'https://www.jisc.ac.uk', relevantSystems: ['sits', 'workday_student', 'sjms'] },
  { title: 'Gartner Hype Cycle for Education Technology 2024', publisher: 'Gartner', year: 2024, category: 'Analyst Report', tags: ['edtech', 'hype cycle', 'emerging technology', 'AI'], summary: 'Annual Hype Cycle placing AI tutors and generative AI at Peak of Inflated Expectations. Adaptive learning on slope of enlightenment. Cloud SIS at plateau. Learning analytics mainstream.', url: 'https://www.gartner.com', relevantSystems: ['workday_student', 'canvas', 'brightspace', 'salesforce_edu'] },
  { title: 'Total Cost of Ownership: SIS Comparison Study', publisher: 'EDUCAUSE', year: 2023, category: 'Benchmark', tags: ['TCO', 'cost', 'SIS', 'financial analysis'], summary: 'TCO analysis of 8 SIS platforms across 50 US institutions. Findings: cloud SIS averages $28/student/year vs on-premise $45/student/year when all costs included. Implementation cost averages 3x first-year licence.', url: 'https://www.educause.edu', relevantSystems: ['banner', 'workday_student', 'peoplesoft', 'colleague'] },
  { title: 'Deakin University SITS to Unit4 Migration', publisher: 'Unit4', year: 2023, category: 'Case Study', tags: ['Australia', 'migration', 'cloud SIS'], summary: 'Deakin University (60,000 students) successfully migrated to Unit4 Student Management in 24 months. First major SITS replacement in Australasia. Budget: AUD 18M. Outcomes: reduced administrative workload by 30%.', url: 'https://www.unit4.com', relevantSystems: ['sits', 'unit4'] },
  { title: 'Accessibility in Learning Technology: WCAG Compliance Benchmark', publisher: 'AbilityNet', year: 2024, category: 'Benchmark', tags: ['accessibility', 'WCAG', 'LMS', 'inclusion'], summary: 'Independent accessibility audit of 6 major LMS platforms against WCAG 2.1 AA. D2L Brightspace ranked highest overall. Canvas scored well. Moodle improved significantly in v4.x. Aula strong on community features.', url: 'https://www.abilitynet.org.uk', relevantSystems: ['brightspace', 'canvas', 'moodle', 'aula', 'blackboard'] },
  { title: 'Tribal Group Annual Results and Strategic Outlook 2024', publisher: 'Tribal Group', year: 2024, category: 'Analyst Report', tags: ['SITS', 'Tribal', 'cloud migration', 'UK market'], summary: 'Tribal Group financial results showing SITS cloud migration accelerating. 40% of UK SITS customers now on cloud-hosted. Revenue from SITS Vision Cloud grew 45% YoY. Australia market strengthening.', url: 'https://www.tribalgroup.com', relevantSystems: ['sits'] },
];

export async function seedVendorProfiles(prisma: PrismaClient): Promise<void> {
  console.log('Seeding vendor profiles...');

  for (const profileData of profiles) {
    const system = await prisma.vendorSystem.findFirst({
      where: { name: { contains: profileData.systemNameContains } },
    });

    if (!system) {
      console.warn(`System not found for: ${profileData.systemNameContains} — skipping`);
      continue;
    }

    await prisma.vendorProfile.upsert({
      where: { systemId: system.id },
      create: {
        systemId: system.id,
        foundedYear: profileData.foundedYear ?? null,
        headquarters: profileData.headquarters ?? null,
        employees: profileData.employees ?? null,
        marketShare: profileData.marketShare ?? null,
        gartnerPosition: profileData.gartnerPosition ?? null,
        deploymentModel: profileData.deploymentModel,
        techStack: profileData.techStack ?? null,
        apiStandards: profileData.apiStandards,
        integrationProtocols: profileData.integrationProtocols,
        certifications: profileData.certifications,
        pricingModel: profileData.pricingModel ?? null,
        typicalCostRange: profileData.typicalCostRange ?? null,
        implementationTime: profileData.implementationTime ?? null,
        keyStrengths: profileData.keyStrengths,
        knownLimitations: profileData.knownLimitations,
        recentNews: profileData.recentNews ?? null,
      },
      update: {
        foundedYear: profileData.foundedYear ?? null,
        headquarters: profileData.headquarters ?? null,
        employees: profileData.employees ?? null,
        marketShare: profileData.marketShare ?? null,
        gartnerPosition: profileData.gartnerPosition ?? null,
        deploymentModel: profileData.deploymentModel,
        techStack: profileData.techStack ?? null,
        apiStandards: profileData.apiStandards,
        integrationProtocols: profileData.integrationProtocols,
        certifications: profileData.certifications,
        pricingModel: profileData.pricingModel ?? null,
        typicalCostRange: profileData.typicalCostRange ?? null,
        implementationTime: profileData.implementationTime ?? null,
        keyStrengths: profileData.keyStrengths,
        knownLimitations: profileData.knownLimitations,
        recentNews: profileData.recentNews ?? null,
        lastUpdated: new Date(),
      },
    });
  }

  console.log(`Seeded ${profiles.length} vendor profiles`);

  // Seed research items
  console.log('Seeding research items...');
  for (const item of researchItems) {
    await prisma.researchItem.create({
      data: {
        title: item.title,
        publisher: item.publisher,
        year: item.year,
        category: item.category,
        tags: item.tags,
        summary: item.summary ?? null,
        url: item.url ?? null,
        relevantSystems: item.relevantSystems,
      },
    });
  }
  console.log(`Seeded ${researchItems.length} research items`);

  // Seed scoring methodology
  console.log('Seeding scoring methodology...');
  const methodologyRecords = [
    {
      category: 'scoring_model',
      content: {
        title: 'HERM Capability Scoring Model',
        overview: 'Each system is scored against 165 HERM v3.1 business capabilities using a three-tier model.',
        tiers: [
          {
            value: 100,
            label: 'Full Coverage',
            description: 'The system fully delivers this capability natively, out-of-the-box, without significant customisation.',
            criteria: [
              'Capability is available in the standard product',
              'No additional modules or licences required',
              'Functionality is production-ready and widely deployed',
              'Evidence from analyst reports, case studies, or official documentation',
            ],
          },
          {
            value: 50,
            label: 'Partial Coverage',
            description: 'The system provides partial coverage — either through a limited implementation, requiring add-ons, or via partner integrations.',
            criteria: [
              'Core functionality present but limited in scope',
              'Requires additional configuration, modules, or third-party tools',
              'Functionality exists but is not the primary use case',
              'Roadmap commitment with partial current delivery',
            ],
          },
          {
            value: 0,
            label: 'No Coverage',
            description: 'The system does not cover this capability, or coverage requires a separate product entirely.',
            criteria: [
              'No native functionality for this capability',
              'Would require a separate, independently licensed system',
              'Explicitly out of scope for this product category',
              'No roadmap commitment found in public documentation',
            ],
          },
        ],
        weightingNote: 'All capabilities are currently weighted equally. Future releases will support institution-specific weighting via the Capability Basket feature.',
      },
    },
    {
      category: 'evidence_types',
      content: {
        title: 'Evidence Types and Sources',
        overview: 'Scores are based on evidence from multiple source types, ranked by reliability.',
        sources: [
          {
            type: 'Official Documentation',
            reliability: 'High',
            description: 'Vendor product documentation, datasheets, and feature lists from official vendor websites.',
            examples: ['Product feature pages', 'Technical specifications', 'Release notes', 'API documentation'],
          },
          {
            type: 'Analyst Reports',
            reliability: 'High',
            description: 'Independent analysis from recognised HE technology analysts.',
            examples: ['Gartner Magic Quadrant', 'Forrester Wave', 'IDC MarketScape', 'Ovum/Omdia reports', 'EDUCAUSE research'],
          },
          {
            type: 'Case Studies',
            reliability: 'Medium-High',
            description: 'Published implementation case studies from HE institutions.',
            examples: ['Vendor-published case studies', 'Jisc case studies', 'EDUCAUSE case studies', 'Conference presentations'],
          },
          {
            type: 'Sector Surveys',
            reliability: 'Medium',
            description: 'Survey-based research from HE sector bodies.',
            examples: ['UCISA Digital Capabilities Survey', 'Jisc Technology Reports', 'Times Higher Education surveys'],
          },
          {
            type: 'Community Knowledge',
            reliability: 'Medium',
            description: 'Practitioner knowledge from the HE technology community.',
            examples: ['UCISA community forums', 'LinkedIn HE groups', 'Conference discussions', 'Practitioner interviews'],
          },
        ],
        updateFrequency: 'Scores are reviewed annually, or when major product releases occur. Version history tracks score changes over time.',
      },
    },
    {
      category: 'review_process',
      content: {
        title: 'Review and Update Process',
        overview: 'How the HERM Platform scores are maintained and quality-assured.',
        process: [
          {
            stage: 1,
            name: 'Initial Scoring',
            description: 'Scores are initially set based on desk research using official documentation and analyst reports.',
            frequency: 'One-time per system onboarding',
          },
          {
            stage: 2,
            name: 'Community Review',
            description: 'Practitioners with experience of the system are invited to review and challenge scores.',
            frequency: 'Ongoing — via Submit Evidence feature',
          },
          {
            stage: 3,
            name: 'Annual Refresh',
            description: 'All scores reviewed against latest analyst reports and vendor documentation.',
            frequency: 'Annual — typically Q1 each year',
          },
          {
            stage: 4,
            name: 'Major Release Update',
            description: 'Scores updated when a major product version is released that changes capability coverage.',
            frequency: 'Event-driven — following vendor announcements',
          },
        ],
        governance: {
          editorialBoard: 'A panel of UK HE IT professionals oversees scoring decisions for disputed capabilities.',
          vendorInput: 'Vendors may submit evidence but cannot directly edit scores. All vendor submissions are reviewed by the editorial board.',
          transparency: 'All score changes are logged with reason codes. Version history is publicly visible.',
        },
      },
    },
    {
      category: 'faq',
      content: {
        title: 'Frequently Asked Questions',
        questions: [
          {
            q: 'Why are scores 0, 50, or 100 only?',
            a: 'The three-tier model (None/Partial/Full) is intentionally simple to ensure consistency across 165 capabilities and 21 systems. Finer granularity would require deeper per-installation knowledge that is impractical at this scale. The model is designed for procurement shortlisting, not final selection — detailed RFP processes should follow for shortlisted systems.',
          },
          {
            q: 'Do the scores represent a specific version of each product?',
            a: 'Scores represent the generally available (GA) version at the time of last review. The Version History feature (Phase 2) will track capability changes across major releases. Check the lastUpdated date on each system profile.',
          },
          {
            q: 'My institution uses Banner/SITS/[other system] and it does X — why is it scored 0?',
            a: 'Scores represent out-of-the-box capability without bespoke customisation. Many institutions have developed custom extensions that deliver capabilities not present in the standard product. These are valuable but are institution-specific and not transferable. Use the Submit Evidence button to share your experience.',
          },
          {
            q: 'Why is SJMS included alongside commercial systems?',
            a: 'SJMS is the internal system being built to HERM v3.1 specification. Including it provides a live benchmark showing current coverage and gap areas. It serves as a reference point for understanding what "full UK HE compliance" requires.',
          },
          {
            q: 'How do I use this for procurement?',
            a: 'Use the Capability Basket to define your Must Have / Should Have / Could Have requirements. Score each basket item by priority. The system will calculate weighted scores for each vendor against your specific requirements — giving a procurement-specific ranking rather than the overall HERM score.',
          },
          {
            q: 'Are LMS scores comparable to SIS scores?',
            a: 'Not directly. Different system categories (SIS, LMS, CRM, HCM) are designed for different HERM capability families. The overall score reflects total HERM coverage but should be interpreted within category. Use the Family-level scores (e.g., Learning & Teaching vs Financial Management) for meaningful cross-category comparisons.',
          },
          {
            q: 'How current is the data?',
            a: 'Each system profile shows a lastUpdated date. The platform is updated quarterly with a full annual refresh each January. Major version releases trigger immediate score reviews for the affected system.',
          },
          {
            q: 'Can vendors update their own scores?',
            a: 'No. Vendors can submit evidence for editorial board review but cannot directly modify scores. This maintains editorial independence. Contact us if you are a vendor and believe a score is incorrect.',
          },
        ],
      },
    },
  ];

  for (const record of methodologyRecords) {
    await prisma.scoringMethodology.upsert({
      where: { category: record.category },
      create: { category: record.category, content: record.content },
      update: { content: record.content },
    });
  }
  console.log(`Seeded ${methodologyRecords.length} scoring methodology records`);
}
