// Phase 14.3 — Business Case PDF render. Procurement officers asked for a
// board-pack export so the generated business case can be circulated to
// SLT without copy-pasting markdown into Word. Pilot scope: Business Case
// only — RFP/ITT carries richer tables and is deferred to a follow-up
// (see queue Out of scope).
//
// Tooling choice: pdfkit (programmatic layout, ~150 KB bundle) over
// puppeteer + headless Chrome (~150 MB, busts Vercel's function bundle
// limit). The Business Case body is structured Markdown — pdfkit can
// render it without HTML round-trip, and the output is plain procurement
// prose that doesn't need pixel-faithful HTML reproduction.
//
// The Markdown subset we render is intentionally narrow: headings (`#`,
// `##`, `###`), bold (`**text**`), bullet lists (`- `), and tables
// (`| col | col |` with a separator row). That covers ~95% of the
// Business Case template content; anything outside it falls through as
// plain text. Adding richer markdown features as the templates evolve
// is a deliberate next-step.

import PDFDocument from 'pdfkit';
import { PRODUCT } from '../../lib/branding';

export interface PdfDocumentSection {
  id: string;
  title: string;
  content: string;
  order: number;
}

/**
 * Phase 16.13 — Enterprise white-label override. When set AND the
 * caller is on Enterprise tier, the renderer swaps the default
 * accent colour + footer text for the institution's preferences.
 *
 * Tier check is the controller's responsibility — this module
 * trusts that if `branding` is passed, the caller has already
 * verified Enterprise tier. Free / Pro callers must NEVER pass
 * `branding` — pass `undefined` instead.
 */
export interface BrandingOverride {
  primaryColor?: string | null;
  secondaryColor?: string | null;
  footerText?: string | null;
  logoUrl?: string | null;
}

export interface RenderBusinessCaseInput {
  title: string;
  sections: PdfDocumentSection[];
  /** Stamped on the cover (e.g. "Generated 2026-05-10 for King's College"). */
  metaLine?: string;
  /** Phase 16.13 — Enterprise-only branding override. See above. */
  branding?: BrandingOverride;
}

const PAGE_MARGIN = 56; // ~20 mm on A4
const COLOUR_BODY = '#1f2937';
const COLOUR_MUTED = '#6b7280';
const COLOUR_ACCENT_DEFAULT = '#0d9488'; // teal-600 — matches the SPA theme
const COLOUR_RULE = '#e5e7eb';

// Body uses a pdfkit built-in (Helvetica). Switching to a real font is a
// follow-up — the built-ins have no licensing footprint and ship with
// pdfkit so the bundle stays small.

export async function renderBusinessCasePdf(
  input: RenderBusinessCaseInput,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: {
          top: PAGE_MARGIN,
          bottom: PAGE_MARGIN,
          left: PAGE_MARGIN,
          right: PAGE_MARGIN,
        },
        info: {
          Title: input.title,
          Producer: PRODUCT.name,
          Creator: `${PRODUCT.name} — pdfkit`,
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Phase 16.13 — resolve accent colour + footer text from the
      // optional branding override. Falls back to platform defaults
      // for any field not set. The override is trusted at this level
      // — the controller has already verified Enterprise tier.
      const accentColour = input.branding?.primaryColor ?? COLOUR_ACCENT_DEFAULT;
      const footerText = input.branding?.footerText
        ?? `Generated by ${PRODUCT.name} — ${PRODUCT.longName}`;

      renderCover(doc, input, accentColour, footerText);
      const sorted = [...input.sections].sort((a, b) => a.order - b.order);
      for (const section of sorted) {
        doc.addPage();
        renderSection(doc, section, accentColour);
      }
      doc.end();
    } catch (err) {
      reject(err as Error);
    }
  });
}

function renderCover(
  doc: PDFKit.PDFDocument,
  input: RenderBusinessCaseInput,
  accentColour: string,
  footerText: string,
): void {
  doc.fillColor(accentColour).fontSize(10).font('Helvetica-Bold');
  doc.text('BUSINESS CASE', { align: 'left' });
  doc.moveDown(0.5);

  doc.fillColor(COLOUR_BODY).fontSize(28).font('Helvetica-Bold');
  doc.text(input.title, { align: 'left' });
  doc.moveDown(1);

  if (input.metaLine) {
    doc.fillColor(COLOUR_MUTED).fontSize(11).font('Helvetica');
    doc.text(input.metaLine, { align: 'left' });
  }

  // Bottom-anchored rule + footer for visual polish without relying on
  // the table-of-contents sections.
  const ruleY = doc.page.height - PAGE_MARGIN - 60;
  doc.moveTo(PAGE_MARGIN, ruleY)
    .lineTo(doc.page.width - PAGE_MARGIN, ruleY)
    .strokeColor(COLOUR_RULE).lineWidth(0.5).stroke();
  doc.fillColor(COLOUR_MUTED).fontSize(9).font('Helvetica');
  doc.text(footerText, PAGE_MARGIN, ruleY + 8, {
    width: doc.page.width - PAGE_MARGIN * 2,
    align: 'center',
  });
}

function renderSection(doc: PDFKit.PDFDocument, section: PdfDocumentSection, accentColour: string): void {
  doc.fillColor(accentColour).fontSize(10).font('Helvetica-Bold');
  doc.text(`SECTION ${section.order}`);
  doc.moveDown(0.2);
  doc.fillColor(COLOUR_BODY).fontSize(20).font('Helvetica-Bold');
  doc.text(section.title);
  doc.moveDown(0.6);

  renderMarkdown(doc, section.content);
}

// ── Tiny Markdown renderer ────────────────────────────────────────────────
//
// pdfkit has no Markdown support; we walk lines and dispatch by the first
// few characters. Strict enough that a template with malformed tables or
// uneven separators still produces a reasonable PDF (falls through to
// plain-text rendering).

interface TableBuffer {
  headers: string[];
  rows: string[][];
}

function renderMarkdown(doc: PDFKit.PDFDocument, content: string): void {
  const lines = content.split('\n');
  let table: TableBuffer | null = null;
  let i = 0;
  while (i < lines.length) {
    const raw = lines[i] ?? '';
    const line = raw.trimEnd();

    // Tables: a header row + a separator row (`|---|---|`) + body rows
    if (isTableRow(line) && i + 1 < lines.length && isTableSeparator(lines[i + 1] ?? '')) {
      table = { headers: parseTableRow(line), rows: [] };
      i += 2; // skip header + separator
      while (i < lines.length && isTableRow(lines[i] ?? '')) {
        table.rows.push(parseTableRow(lines[i] ?? ''));
        i += 1;
      }
      renderTable(doc, table);
      table = null;
      continue;
    }

    if (line.startsWith('### ')) {
      doc.moveDown(0.4);
      doc.fillColor(COLOUR_BODY).fontSize(13).font('Helvetica-Bold');
      doc.text(line.slice(4));
      doc.moveDown(0.2);
    } else if (line.startsWith('## ')) {
      doc.moveDown(0.5);
      doc.fillColor(COLOUR_BODY).fontSize(15).font('Helvetica-Bold');
      doc.text(line.slice(3));
      doc.moveDown(0.3);
    } else if (line.startsWith('# ')) {
      doc.moveDown(0.6);
      doc.fillColor(COLOUR_BODY).fontSize(17).font('Helvetica-Bold');
      doc.text(line.slice(2));
      doc.moveDown(0.3);
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      renderInlineParagraph(doc, '• ' + line.slice(2), { indent: 14 });
    } else if (line === '') {
      doc.moveDown(0.4);
    } else {
      renderInlineParagraph(doc, line);
    }
    i += 1;
  }
}

function renderInlineParagraph(
  doc: PDFKit.PDFDocument,
  line: string,
  options: { indent?: number } = {},
): void {
  // Inline bold via `**text**`. Split into fragments and render each with
  // the appropriate font. pdfkit's `continued: true` keeps the cursor on
  // the same line so the segments wrap naturally.
  const fragments = splitBold(line);
  doc.fillColor(COLOUR_BODY).fontSize(11);
  if (options.indent) {
    doc.text('', PAGE_MARGIN + options.indent, doc.y, { continued: false });
  }
  fragments.forEach((frag, idx) => {
    doc.font(frag.bold ? 'Helvetica-Bold' : 'Helvetica');
    doc.text(frag.text, { continued: idx < fragments.length - 1 });
  });
}

interface InlineFragment {
  text: string;
  bold: boolean;
}

function splitBold(line: string): InlineFragment[] {
  const out: InlineFragment[] = [];
  const re = /\*\*(.+?)\*\*/g;
  let lastIdx = 0;
  let match: RegExpExecArray | null;
  while ((match = re.exec(line)) !== null) {
    if (match.index > lastIdx) {
      out.push({ text: line.slice(lastIdx, match.index), bold: false });
    }
    out.push({ text: match[1] ?? '', bold: true });
    lastIdx = match.index + match[0].length;
  }
  if (lastIdx < line.length) {
    out.push({ text: line.slice(lastIdx), bold: false });
  }
  if (out.length === 0) {
    out.push({ text: line, bold: false });
  }
  return out;
}

function isTableRow(line: string): boolean {
  const trimmed = line.trim();
  return trimmed.startsWith('|') && trimmed.endsWith('|');
}

function isTableSeparator(line: string): boolean {
  if (!isTableRow(line)) return false;
  const cells = parseTableRow(line);
  return cells.every((c) => /^:?-{2,}:?$/.test(c.trim()));
}

function parseTableRow(line: string): string[] {
  const trimmed = line.trim();
  return trimmed
    .slice(1, -1)
    .split('|')
    .map((cell) => cell.trim());
}

function renderTable(doc: PDFKit.PDFDocument, table: TableBuffer): void {
  const cols = table.headers.length;
  if (cols === 0) return;
  const usable = doc.page.width - PAGE_MARGIN * 2;
  const colWidth = usable / cols;
  const rowPadding = 4;

  doc.moveDown(0.4);
  let y = doc.y;

  // Header row
  doc.fillColor(COLOUR_BODY).font('Helvetica-Bold').fontSize(10);
  const headerHeight = rowHeight(doc, table.headers, colWidth);
  drawRowBackground(doc, PAGE_MARGIN, y, usable, headerHeight, '#f3f4f6');
  table.headers.forEach((cell, idx) => {
    doc.text(stripBold(cell), PAGE_MARGIN + idx * colWidth + rowPadding, y + rowPadding, {
      width: colWidth - rowPadding * 2,
    });
  });
  y += headerHeight;

  // Body rows
  doc.fillColor(COLOUR_BODY).font('Helvetica').fontSize(10);
  for (const row of table.rows) {
    const padded: string[] = [];
    for (let c = 0; c < cols; c += 1) padded.push(row[c] ?? '');
    const h = rowHeight(doc, padded, colWidth);
    if (y + h > doc.page.height - PAGE_MARGIN) {
      doc.addPage();
      y = doc.y;
    }
    padded.forEach((cell, idx) => {
      doc.font(/^\*\*.+\*\*$/.test(cell) ? 'Helvetica-Bold' : 'Helvetica');
      doc.text(stripBold(cell), PAGE_MARGIN + idx * colWidth + rowPadding, y + rowPadding, {
        width: colWidth - rowPadding * 2,
      });
    });
    doc.moveTo(PAGE_MARGIN, y + h)
      .lineTo(PAGE_MARGIN + usable, y + h)
      .strokeColor(COLOUR_RULE).lineWidth(0.5).stroke();
    y += h;
  }

  // Reset cursor below the table so subsequent paragraphs render in the
  // expected place. pdfkit's text() calls with explicit (x, y) leave the
  // internal cursor in an awkward state otherwise.
  doc.x = PAGE_MARGIN;
  doc.y = y + 6;
  doc.font('Helvetica').fontSize(11).fillColor(COLOUR_BODY);
}

function rowHeight(
  doc: PDFKit.PDFDocument,
  cells: string[],
  colWidth: number,
): number {
  const padding = 8;
  const max = cells.reduce((acc, cell) => {
    const h = doc.heightOfString(stripBold(cell), { width: colWidth - padding });
    return Math.max(acc, h);
  }, 0);
  return max + padding;
}

function drawRowBackground(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  width: number,
  height: number,
  fill: string,
): void {
  doc.save();
  doc.rect(x, y, width, height).fill(fill);
  doc.restore();
}

function stripBold(cell: string): string {
  return cell.replace(/\*\*(.+?)\*\*/g, '$1');
}
