-- Phase 7 multi-framework catch-up.
--
-- Background: Phase 7 ("HERM + FHE multi-framework transformation",
-- progress/phase7-multi-framework-transformation.md) restructured the
-- capability data model from `HermFamily`/`HermCapability`/`Score` (single-
-- framework) into `Framework`/`FrameworkDomain`/`Capability`/`CapabilityScore`
-- (multi-framework, with `FrameworkMapping`+`CapabilityMapping` for cross-
-- framework lookups). The schema change was applied via `db:push` only;
-- no migration was ever generated, so prisma/migrations/ was stuck at the
-- pre-Phase-7 schema.
--
-- This migration bridges the gap so `prisma migrate deploy` from a fresh
-- Postgres reaches the current schema.prisma state. Generated by:
--
--   prisma migrate diff \
--     --from-migrations prisma/migrations \
--     --to-schema-datamodel prisma/schema.prisma \
--     --script
--
-- ⚠ Existing deployments (any DB that was bootstrapped with `db:push`
-- from the post-Phase-7 schema.prisma) ALREADY have the target shape and
-- do NOT have the legacy `HermFamily`/`HermCapability`/`Score` tables to
-- drop. Running this migration against them would fail. For those, the
-- operator must run a one-time baseline:
--
--   for m in $(ls prisma/migrations | grep -v migration_lock); do
--     npx prisma migrate resolve --applied "$m"
--   done
--
-- See RUNBOOK "Apply migrations (prod / staging) → First-time baseline".

-- DropForeignKey
ALTER TABLE "BasketItem" DROP CONSTRAINT "BasketItem_capabilityId_fkey";

-- DropForeignKey
ALTER TABLE "EvaluationDomainAssignment" DROP CONSTRAINT "EvaluationDomainAssignment_familyId_fkey";

-- DropForeignKey
ALTER TABLE "HermCapability" DROP CONSTRAINT "HermCapability_familyId_fkey";

-- DropForeignKey
ALTER TABLE "Score" DROP CONSTRAINT "Score_capabilityId_fkey";

-- DropForeignKey
ALTER TABLE "Score" DROP CONSTRAINT "Score_systemId_fkey";

-- DropForeignKey
ALTER TABLE "VersionScore" DROP CONSTRAINT "VersionScore_capabilityId_fkey";

-- DropIndex
DROP INDEX "EvaluationDomainAssignment_projectId_familyId_key";

-- DropIndex
DROP INDEX "VersionScore_versionId_capabilityId_key";

-- AlterTable
ALTER TABLE "CapabilityBasket" ADD COLUMN     "frameworkId" TEXT;

-- AlterTable
ALTER TABLE "ChatMessage" ADD COLUMN     "userId" TEXT;

-- AlterTable
ALTER TABLE "EvaluationDomainAssignment" DROP COLUMN "familyId",
ADD COLUMN     "domainId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "EvaluationProject" ADD COLUMN     "frameworkId" TEXT;

-- AlterTable
ALTER TABLE "ProcurementEvaluation" DROP COLUMN "hermScore",
ADD COLUMN     "frameworkScore" DECIMAL(5,2);

-- AlterTable
ALTER TABLE "VersionScore" ADD COLUMN     "frameworkId" TEXT NOT NULL;

-- DropTable
DROP TABLE "HermCapability";

-- DropTable
DROP TABLE "HermFamily";

-- DropTable
DROP TABLE "Score";

-- CreateTable
CREATE TABLE "Framework" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "publisher" TEXT NOT NULL,
    "description" TEXT,
    "licenceType" TEXT NOT NULL,
    "licenceNotice" TEXT,
    "licenceUrl" TEXT,
    "isPublic" BOOLEAN NOT NULL DEFAULT false,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "domainCount" INTEGER NOT NULL DEFAULT 0,
    "capabilityCount" INTEGER NOT NULL DEFAULT 0,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Framework_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FrameworkDomain" (
    "id" TEXT NOT NULL,
    "frameworkId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "description" TEXT,
    "sortOrder" INTEGER NOT NULL,
    "colour" TEXT,
    "capabilityCount" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "FrameworkDomain_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Capability" (
    "id" TEXT NOT NULL,
    "frameworkId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "domainId" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL,
    "level" INTEGER NOT NULL DEFAULT 1,
    "parentId" TEXT,

    CONSTRAINT "Capability_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CapabilityScore" (
    "id" TEXT NOT NULL,
    "frameworkId" TEXT NOT NULL,
    "systemId" TEXT NOT NULL,
    "capabilityId" TEXT NOT NULL,
    "value" INTEGER NOT NULL,
    "evidence" TEXT,
    "source" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "scoredBy" TEXT,
    "scoredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CapabilityScore_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FrameworkMapping" (
    "id" TEXT NOT NULL,
    "sourceFrameworkId" TEXT NOT NULL,
    "targetFrameworkId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "mappingType" TEXT NOT NULL,
    "createdBy" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FrameworkMapping_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CapabilityMapping" (
    "id" TEXT NOT NULL,
    "mappingId" TEXT NOT NULL,
    "sourceCapabilityId" TEXT NOT NULL,
    "targetCapabilityId" TEXT NOT NULL,
    "strength" TEXT NOT NULL DEFAULT 'partial',
    "confidence" INTEGER NOT NULL DEFAULT 50,
    "notes" TEXT,

    CONSTRAINT "CapabilityMapping_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Framework_slug_key" ON "Framework"("slug");

-- CreateIndex
CREATE INDEX "Framework_isPublic_idx" ON "Framework"("isPublic");

-- CreateIndex
CREATE INDEX "Framework_isDefault_idx" ON "Framework"("isDefault");

-- CreateIndex
CREATE INDEX "FrameworkDomain_frameworkId_idx" ON "FrameworkDomain"("frameworkId");

-- CreateIndex
CREATE UNIQUE INDEX "FrameworkDomain_frameworkId_code_key" ON "FrameworkDomain"("frameworkId", "code");

-- CreateIndex
CREATE INDEX "Capability_frameworkId_idx" ON "Capability"("frameworkId");

-- CreateIndex
CREATE INDEX "Capability_domainId_idx" ON "Capability"("domainId");

-- CreateIndex
CREATE INDEX "Capability_parentId_idx" ON "Capability"("parentId");

-- CreateIndex
CREATE UNIQUE INDEX "Capability_frameworkId_code_key" ON "Capability"("frameworkId", "code");

-- CreateIndex
CREATE INDEX "CapabilityScore_frameworkId_idx" ON "CapabilityScore"("frameworkId");

-- CreateIndex
CREATE INDEX "CapabilityScore_systemId_idx" ON "CapabilityScore"("systemId");

-- CreateIndex
CREATE INDEX "CapabilityScore_capabilityId_idx" ON "CapabilityScore"("capabilityId");

-- CreateIndex
CREATE UNIQUE INDEX "CapabilityScore_frameworkId_systemId_capabilityId_version_key" ON "CapabilityScore"("frameworkId", "systemId", "capabilityId", "version");

-- CreateIndex
CREATE INDEX "FrameworkMapping_sourceFrameworkId_idx" ON "FrameworkMapping"("sourceFrameworkId");

-- CreateIndex
CREATE INDEX "FrameworkMapping_targetFrameworkId_idx" ON "FrameworkMapping"("targetFrameworkId");

-- CreateIndex
CREATE UNIQUE INDEX "FrameworkMapping_sourceFrameworkId_targetFrameworkId_name_key" ON "FrameworkMapping"("sourceFrameworkId", "targetFrameworkId", "name");

-- CreateIndex
CREATE INDEX "CapabilityMapping_mappingId_idx" ON "CapabilityMapping"("mappingId");

-- CreateIndex
CREATE INDEX "CapabilityMapping_sourceCapabilityId_idx" ON "CapabilityMapping"("sourceCapabilityId");

-- CreateIndex
CREATE INDEX "CapabilityMapping_targetCapabilityId_idx" ON "CapabilityMapping"("targetCapabilityId");

-- CreateIndex
CREATE UNIQUE INDEX "CapabilityMapping_mappingId_sourceCapabilityId_targetCapabi_key" ON "CapabilityMapping"("mappingId", "sourceCapabilityId", "targetCapabilityId");

-- CreateIndex
CREATE INDEX "CapabilityBasket_frameworkId_idx" ON "CapabilityBasket"("frameworkId");

-- CreateIndex
CREATE INDEX "ChatMessage_userId_idx" ON "ChatMessage"("userId");

-- CreateIndex
CREATE INDEX "ChatMessage_sessionId_userId_idx" ON "ChatMessage"("sessionId", "userId");

-- CreateIndex
CREATE UNIQUE INDEX "EvaluationDomainAssignment_projectId_domainId_key" ON "EvaluationDomainAssignment"("projectId", "domainId");

-- CreateIndex
CREATE INDEX "EvaluationProject_frameworkId_idx" ON "EvaluationProject"("frameworkId");

-- CreateIndex
CREATE INDEX "VersionScore_frameworkId_idx" ON "VersionScore"("frameworkId");

-- CreateIndex
CREATE UNIQUE INDEX "VersionScore_frameworkId_versionId_capabilityId_key" ON "VersionScore"("frameworkId", "versionId", "capabilityId");

-- AddForeignKey
ALTER TABLE "FrameworkDomain" ADD CONSTRAINT "FrameworkDomain_frameworkId_fkey" FOREIGN KEY ("frameworkId") REFERENCES "Framework"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Capability" ADD CONSTRAINT "Capability_frameworkId_fkey" FOREIGN KEY ("frameworkId") REFERENCES "Framework"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Capability" ADD CONSTRAINT "Capability_domainId_fkey" FOREIGN KEY ("domainId") REFERENCES "FrameworkDomain"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Capability" ADD CONSTRAINT "Capability_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Capability"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CapabilityScore" ADD CONSTRAINT "CapabilityScore_frameworkId_fkey" FOREIGN KEY ("frameworkId") REFERENCES "Framework"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CapabilityScore" ADD CONSTRAINT "CapabilityScore_systemId_fkey" FOREIGN KEY ("systemId") REFERENCES "VendorSystem"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CapabilityScore" ADD CONSTRAINT "CapabilityScore_capabilityId_fkey" FOREIGN KEY ("capabilityId") REFERENCES "Capability"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CapabilityBasket" ADD CONSTRAINT "CapabilityBasket_frameworkId_fkey" FOREIGN KEY ("frameworkId") REFERENCES "Framework"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BasketItem" ADD CONSTRAINT "BasketItem_capabilityId_fkey" FOREIGN KEY ("capabilityId") REFERENCES "Capability"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VersionScore" ADD CONSTRAINT "VersionScore_frameworkId_fkey" FOREIGN KEY ("frameworkId") REFERENCES "Framework"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VersionScore" ADD CONSTRAINT "VersionScore_capabilityId_fkey" FOREIGN KEY ("capabilityId") REFERENCES "Capability"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EvaluationProject" ADD CONSTRAINT "EvaluationProject_frameworkId_fkey" FOREIGN KEY ("frameworkId") REFERENCES "Framework"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EvaluationDomainAssignment" ADD CONSTRAINT "EvaluationDomainAssignment_domainId_fkey" FOREIGN KEY ("domainId") REFERENCES "FrameworkDomain"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FrameworkMapping" ADD CONSTRAINT "FrameworkMapping_sourceFrameworkId_fkey" FOREIGN KEY ("sourceFrameworkId") REFERENCES "Framework"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FrameworkMapping" ADD CONSTRAINT "FrameworkMapping_targetFrameworkId_fkey" FOREIGN KEY ("targetFrameworkId") REFERENCES "Framework"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CapabilityMapping" ADD CONSTRAINT "CapabilityMapping_mappingId_fkey" FOREIGN KEY ("mappingId") REFERENCES "FrameworkMapping"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CapabilityMapping" ADD CONSTRAINT "CapabilityMapping_sourceCapabilityId_fkey" FOREIGN KEY ("sourceCapabilityId") REFERENCES "Capability"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CapabilityMapping" ADD CONSTRAINT "CapabilityMapping_targetCapabilityId_fkey" FOREIGN KEY ("targetCapabilityId") REFERENCES "Capability"("id") ON DELETE CASCADE ON UPDATE CASCADE;

