import { useEffect, useState, type FormEvent } from 'react';
import { Palette, Save, Loader2, CheckCircle2, AlertCircle, FileText } from 'lucide-react';
import { Header } from '../components/layout/Header';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { api, ApiError, type BrandingPreferences } from '../lib/api';
import { PRODUCT } from '../lib/branding';

/**
 * Phase 16.13b — Enterprise white-label branding admin UI.
 *
 * Companion to the endpoints shipped in #148 (server) which let
 * Enterprise admins override the PDF export's accent colour, footer
 * text, and logo URL. This page is the UI that calls them.
 *
 * Tier gate: applied at the route level via `<RequireTier
 * tiers={['enterprise']}>` in App.tsx; server re-checks independently.
 *
 * Form behaviour
 * - Empty/blank field on save = clear to platform default (sends `null`).
 * - Save is debounced via the explicit submit button (no autosave) so
 *   a typo in a hex doesn't bork the live PDF render mid-keystroke.
 * - Live preview panel mirrors the rendered PDF cover styling so the
 *   admin can sanity-check before saving.
 */

const HEX_COLOR_RE = /^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;
const DEFAULT_PRIMARY = '#0d9488';   // teal-600, matches render-business-case.ts default
const DEFAULT_SECONDARY = '#1f2937'; // gray-800, body text default
/** Matches `render-business-case.ts` when `footerText` is unset. */
const DEFAULT_FOOTER = `Generated by ${PRODUCT.name} — ${PRODUCT.longName}`;

/** `#rgb` / `#rgba` shorthands → `#rrggbb` for `<input type="color">`. */
function hexToColorInputValue(hex: string): string {
  const raw = hex.trim();
  const body = raw.startsWith('#') ? raw.slice(1) : raw;
  if (body.length === 3) {
    const [r, g, b] = body;
    return `#${r}${r}${g}${g}${b}${b}`.toLowerCase();
  }
  if (body.length === 4) {
    const [r, g, b] = body;
    return `#${r}${r}${g}${g}${b}${b}`.toLowerCase();
  }
  if (body.length === 6) return `#${body}`.toLowerCase();
  if (body.length === 8) return `#${body.slice(0, 6)}`.toLowerCase();
  return raw.slice(0, 7);
}

export function AdminBranding() {
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [saveResult, setSaveResult] = useState<'ok' | 'err' | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);

  const [logoUrl, setLogoUrl] = useState('');
  const [primaryColor, setPrimaryColor] = useState('');
  const [secondaryColor, setSecondaryColor] = useState('');
  const [footerText, setFooterText] = useState('');

  // Field-level validation messages — show inline rather than at the
  // top so the admin can see which field broke.
  const primaryColorValid = primaryColor === '' || HEX_COLOR_RE.test(primaryColor);
  const secondaryColorValid = secondaryColor === '' || HEX_COLOR_RE.test(secondaryColor);
  const footerTextValid = footerText.length <= 200;

  useEffect(() => {
    // Fetch current branding once on mount. queueMicrotask to satisfy
    // the react-hooks/set-state-in-effect rule.
    queueMicrotask(() => {
      void (async () => {
        try {
          const res = await api.getBranding();
          const prefs = res.data.data?.brandingPreferences ?? null;
          setLogoUrl(prefs?.logoUrl ?? '');
          setPrimaryColor(prefs?.primaryColor ?? '');
          setSecondaryColor(prefs?.secondaryColor ?? '');
          setFooterText(prefs?.footerText ?? '');
        } catch (err) {
          setLoadError(err instanceof ApiError ? err.message : 'Failed to load branding');
        } finally {
          setLoading(false);
        }
      })();
    });
  }, []);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setSaveResult(null);
    setSaveError(null);
    if (!primaryColorValid || !secondaryColorValid || !footerTextValid) {
      setSaveResult('err');
      setSaveError('Fix the highlighted fields before saving.');
      return;
    }
    setSaving(true);
    try {
      // Empty string → null (clear back to default). Non-empty → set.
      // Unchanged fields aren't sent — putBranding does read-merge-write
      // server-side so a single-field update preserves the others.
      const payload: Partial<BrandingPreferences> = {
        logoUrl: logoUrl.trim() === '' ? null : logoUrl.trim(),
        primaryColor: primaryColor.trim() === '' ? null : primaryColor.trim(),
        secondaryColor: secondaryColor.trim() === '' ? null : secondaryColor.trim(),
        footerText: footerText.trim() === '' ? null : footerText.trim(),
      };
      await api.putBranding(payload);
      setSaveResult('ok');
    } catch (err) {
      setSaveResult('err');
      setSaveError(err instanceof ApiError ? err.message : 'Failed to save branding');
    } finally {
      setSaving(false);
    }
  }

  // Live preview colours — fall back to defaults when the field is empty
  // or invalid so the preview never shows a broken render.
  const previewPrimary = primaryColorValid && primaryColor !== '' ? primaryColor : DEFAULT_PRIMARY;
  const previewSecondary = secondaryColorValid && secondaryColor !== '' ? secondaryColor : DEFAULT_SECONDARY;
  const previewFooter = footerText.trim() !== '' ? footerText : DEFAULT_FOOTER;

  if (loading) {
    return (
      <div className="space-y-6">
        <Header title="White-label branding" subtitle="Enterprise" />
        <div className="flex items-center gap-2 text-gray-500">
          <Loader2 className="w-4 h-4 animate-spin" /> Loading current branding…
        </div>
      </div>
    );
  }

  if (loadError) {
    return (
      <div className="space-y-6">
        <Header title="White-label branding" subtitle="Enterprise" />
        <Card>
          <div className="flex items-start gap-3 p-3 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800">
            <AlertCircle className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" />
            <p className="text-sm text-red-700 dark:text-red-400">{loadError}</p>
          </div>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <Header
        title="White-label branding"
        subtitle="Customise the look of generated PDFs for your institution"
      />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <div className="flex items-start gap-4 mb-6">
            <div className="w-12 h-12 rounded-xl bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-300 flex items-center justify-center flex-shrink-0">
              <Palette className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                Branding overrides
              </h2>
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                Applied to Business Case PDF exports for your institution.
                Leave any field blank to use the platform default.
              </p>
            </div>
          </div>

          {saveResult === 'ok' && (
            <div className="flex items-start gap-3 p-3 mb-5 rounded-lg bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 mt-0.5 flex-shrink-0" />
              <p className="text-sm text-emerald-800 dark:text-emerald-300">
                Branding saved. Next PDF export will use these settings.
              </p>
            </div>
          )}
          {saveResult === 'err' && saveError && (
            <div className="flex items-start gap-3 p-3 mb-5 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800">
              <AlertCircle className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" />
              <p className="text-sm text-red-700 dark:text-red-400">{saveError}</p>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">
                Logo URL <span className="text-gray-400">(optional)</span>
              </label>
              <input
                type="url"
                value={logoUrl}
                onChange={(e) => setLogoUrl(e.target.value)}
                maxLength={2048}
                placeholder="https://your-institution.ac.uk/brand/logo.png"
                className="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-teal-500"
              />
              <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                URL captured here is stored but the PDF renderer doesn&rsquo;t yet
                embed remote images. Logo-rendering ships in a Phase 17
                follow-up; the field is preserved so you can set it now
                and the renderer picks it up automatically.
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">
                  Primary colour
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="color"
                    value={primaryColorValid && primaryColor ? hexToColorInputValue(primaryColor) : DEFAULT_PRIMARY}
                    onChange={(e) => setPrimaryColor(e.target.value)}
                    aria-label="Primary colour picker"
                    className="h-10 w-10 rounded border border-gray-300 dark:border-gray-600 bg-transparent cursor-pointer"
                  />
                  <input
                    type="text"
                    value={primaryColor}
                    onChange={(e) => setPrimaryColor(e.target.value)}
                    placeholder={DEFAULT_PRIMARY}
                    className={`flex-1 px-3 py-2 text-sm font-mono border rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 ${
                      primaryColorValid
                        ? 'border-gray-300 dark:border-gray-600 focus:ring-teal-500'
                        : 'border-red-400 focus:ring-red-500'
                    }`}
                  />
                </div>
                {!primaryColorValid && (
                  <p className="mt-1 text-xs text-red-600 dark:text-red-400">
                    Must be a hex colour like #3730a3 (3/4/6/8 hex digits).
                  </p>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">
                  Secondary colour
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="color"
                    value={secondaryColorValid && secondaryColor ? hexToColorInputValue(secondaryColor) : DEFAULT_SECONDARY}
                    onChange={(e) => setSecondaryColor(e.target.value)}
                    aria-label="Secondary colour picker"
                    className="h-10 w-10 rounded border border-gray-300 dark:border-gray-600 bg-transparent cursor-pointer"
                  />
                  <input
                    type="text"
                    value={secondaryColor}
                    onChange={(e) => setSecondaryColor(e.target.value)}
                    placeholder={DEFAULT_SECONDARY}
                    className={`flex-1 px-3 py-2 text-sm font-mono border rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 ${
                      secondaryColorValid
                        ? 'border-gray-300 dark:border-gray-600 focus:ring-teal-500'
                        : 'border-red-400 focus:ring-red-500'
                    }`}
                  />
                </div>
                {!secondaryColorValid && (
                  <p className="mt-1 text-xs text-red-600 dark:text-red-400">
                    Must be a hex colour like #a5b4fc.
                  </p>
                )}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">
                Footer text <span className="text-gray-400">(optional, 200 chars max)</span>
              </label>
              <input
                type="text"
                value={footerText}
                onChange={(e) => setFooterText(e.target.value)}
                maxLength={200}
                placeholder={DEFAULT_FOOTER}
                className={`w-full px-3 py-2 text-sm border rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 ${
                  footerTextValid
                    ? 'border-gray-300 dark:border-gray-600 focus:ring-teal-500'
                    : 'border-red-400 focus:ring-red-500'
                }`}
              />
              <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                {footerText.length} / 200 characters
              </p>
            </div>

            <div className="flex justify-end pt-2">
              <Button
                type="submit"
                disabled={
                  saving || !primaryColorValid || !secondaryColorValid || !footerTextValid
                }
              >
                {saving ? (
                  <span className="inline-flex items-center gap-2">
                    <Loader2 className="w-4 h-4 animate-spin" /> Saving…
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-2">
                    <Save className="w-4 h-4" /> Save branding
                  </span>
                )}
              </Button>
            </div>
          </form>
        </Card>

        {/* Live preview — mirrors the PDF cover render in render-business-case.ts.
            Useful for the admin to sanity-check colours + footer text before
            generating a real PDF. Not pixel-perfect; representative only. */}
        <Card>
          <div className="flex items-start gap-3 mb-4">
            <FileText className="w-5 h-5 text-gray-400 mt-0.5" />
            <div>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">PDF cover preview</h2>
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                Representative of the Business Case PDF cover. Updates as you type.
              </p>
            </div>
          </div>
          <div className="rounded-lg border border-gray-200 dark:border-gray-700 bg-white shadow-inner p-8 min-h-[420px] flex flex-col">
            {/* Top accent tag */}
            <div
              className="text-[10px] font-bold tracking-widest uppercase mb-3"
              style={{ color: previewPrimary }}
            >
              BUSINESS CASE
            </div>
            {/* Title */}
            <div
              className="text-3xl font-bold leading-tight"
              style={{ color: previewSecondary }}
            >
              Sample Business Case Title
            </div>
            <div className="text-sm text-gray-500 mt-3">
              Sample Document · Generated {new Date().toLocaleDateString('en-GB')}
            </div>

            {/* Spacer */}
            <div className="flex-1" />

            {/* Bottom rule + footer */}
            <div className="border-t border-gray-200 pt-3 mt-6">
              <p className="text-xs text-gray-500 text-center">{previewFooter}</p>
            </div>
          </div>
          <p className="mt-3 text-xs text-gray-500 dark:text-gray-400">
            Primary colour drives the &ldquo;BUSINESS CASE&rdquo; tag + section
            labels. Secondary colour drives body headings. Footer text replaces
            the default &ldquo;Generated by &hellip;&rdquo; line.
          </p>
        </Card>
      </div>
    </div>
  );
}
